#!/usr/bin/env python3
"""The application working view — what a person works FROM during an application session.

⭐ WHY THIS IS A GENERATED VIEW AND NOT A WORKSHEET (public #27 / dev #233)
---------------------------------------------------------------------------
The dashboard answers "what is true right now"; an application session asks "what am I doing
for the next two hours" — different artifacts, and only the first existed. The evidence for
this one is that it was already being written BY HAND: a per-session worksheet listing, per
role, the posting link, req id, resume variant and the pre-computed answers to the questions
every form asks, filed in a directory meant for interview prep because no better home existed.

The hand-written worksheet is evidence that a VIEW was missing — not that hand-editing is the
right interface. The same session showed what hand-maintained working documents do: the
instruction naming which resume variant to send lived in a free-text field, was written
before the variant decision, and was never rewritten — so the single most time-critical
application was the one missing it. So (D5): records generate this view; nothing here is
authored. ⭐ READ-ONLY BY CONSTRUCTION — regenerate after every recorded change, never edit.
The write path is the session recording data (record.py); the view is where you look.

What each queued role carries (public #27, part B):
  - posting link, req id, posted comp
  - the resume variant to send — from the RECORD (`resume_variant`), never a free-text field
  - pre-computed answers to the form's standard questions, joined from form_answers[] across
    every prior application: the same-employer precedent first (with a conflict flag when two
    applications to one employer answered one question differently), latest elsewhere second
  - per-role cautions: the blocked_until hold and the record's note

Plus the follow-up half of the session (public #27, parts C/D, via trigger.py):
  - submitted applications that no follow-up work names — each is work the submission created
  - sequences whose next step is sendable NOW

⚠️ The printed-resume gap (dev #234) is OPEN and this view does not close it: the variant
named here is a markdown file, and the document actually uploaded is produced outside the
engine. The view says so on every variant line rather than implying the gap is closed.

Usage:
    python3 applying.py              # write <profile>/views/applying.md
    python3 applying.py --stdout     # print instead of writing

Python 3.9+. Standard library only.
"""

import argparse
import os
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import profile_root
import trigger

# Where a pursued role sits when the next act is submitting — validate_data.PLAY_SEQUENCE[0].
QUEUE_PLAY_STAGE = "needs-application"
# Out-of-funnel statuses never queue.
CLOSED_STATUS = ("passed", "expired")

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/applying.py — DO NOT EDIT. This view is read-only by\n"
    "     construction (D5): every fact on it lives on a record, and an edit here is\n"
    "     overwritten by the next regeneration without notice. Change the record in\n"
    "     session (record.py) and regenerate. -->\n")

VARIANT_CAUTION = ("the variant is a markdown file; the document actually uploaded is "
                   "produced outside the engine (dev #234, open) — confirm what you "
                   "attach, and record it on the applications[] row")


def queue(opps):
    """The roles queued to apply — THE one definition, shared with the router row in
    generate_dashboard.py (dev #233): a second copy of this filter would disagree with
    this one later."""
    return [o for o in opps
            if o.get("play_stage") == QUEUE_PLAY_STAGE
            and o.get("verdict") == "pursue"
            and o.get("status") not in CLOSED_STATUS]


def comp_text(comp):
    if isinstance(comp, dict):
        lo, hi = comp.get("min"), comp.get("max")
        if lo or hi:
            return "%s–%s%s" % (lo if lo is not None else "?",
                                hi if hi is not None else "?",
                                " " + comp["note"] if comp.get("note") else "")
        return comp.get("note") or "not posted"
    if isinstance(comp, str) and comp.strip():
        return comp
    return "not posted"


def answer_precedents(opps, companies_by_id):
    """question_key -> list of {company_id, answer, when, opp_id} — every captured form
    answer in the profile, newest first. The join public #27 part E asked for: precedent
    becomes a query instead of re-deriving the rule from scratch per form."""
    out = {}
    for opp in opps:
        for ap in opp.get("applications") or []:
            for ans in ap.get("form_answers") or []:
                qk = ans.get("question_key")
                if not qk:
                    continue
                out.setdefault(qk, []).append({
                    "company_id": opp.get("company_id"),
                    "company": (companies_by_id.get(opp.get("company_id")) or {}).get(
                        "name") or opp.get("company_id"),
                    "answer": ans.get("answer"),
                    "when": ans.get("answered_on") or ap.get("date") or "",
                    "opp_id": opp.get("id")})
    for rows in out.values():
        rows.sort(key=lambda r: r["when"], reverse=True)
    return out


def render(root):
    opps = trigger.load_jsonl(root, "opportunities.jsonl")
    companies_by_id = {c.get("id"): c for c in trigger.load_jsonl(root, "companies.jsonl")}
    rep = trigger.report(root)
    precedents = answer_precedents(opps, companies_by_id)

    q = queue(opps)

    L = [GENERATED_HEADER,
         "# Applying — the working view",
         "",
         "_Generated %s. One section per role queued to apply, then the follow-up work "
         "your submissions have created. Regenerate after every recorded change._" %
         date.today().isoformat(),
         ""]

    L.append("## Queue to apply (%d)" % len(q))
    L.append("")
    if not q:
        L.append("Nothing queued: no pursued role sits at play stage `%s`."
                 % QUEUE_PLAY_STAGE)
        L.append("")
    for o in q:
        comp_id = o.get("company_id")
        company = (companies_by_id.get(comp_id) or {}).get("name") or comp_id
        L.append("### %s — %s" % (o.get("title") or o.get("id"), company))
        L.append("")
        started = next((a for a in o.get("applications") or []
                        if a.get("status") == "started"), None)
        L.append("- **Posting:** %s" % (o.get("jd_url") or "no jd_url on the record"))
        L.append("- **Req id:** %s" % ((started or {}).get("req_id") or "none recorded"))
        L.append("- **Posted comp:** %s" % comp_text(o.get("comp")))
        rv = o.get("resume_variant")
        if rv:
            L.append("- **Resume variant to send:** `%s` — ⚠️ %s" % (rv, VARIANT_CAUTION))
        else:
            L.append("- **Resume variant to send:** ⛔ not decided — decide and record it "
                     "on the opportunity BEFORE opening the form; a variant instruction "
                     "living anywhere else is the free-text leak this view replaced")
        if o.get("blocked_until"):
            L.append("- **Hold:** `%s`" % o["blocked_until"])
        if o.get("note"):
            L.append("- **Caution / note:** %s" % o["note"])
        # the pre-computed answers, same employer first
        own = []
        for qk, rows in sorted(precedents.items()):
            # Same-employer rows INCLUDE this record's own prior applications: two answers
            # to one employer differing is exactly the inconsistency #27-E wants detectable,
            # wherever the two applications live.
            same = [r for r in rows if r["company_id"] == comp_id]
            distinct = {r["answer"] for r in same}
            if len(distinct) > 1:
                own.append("  - `%s`: ⛔ **conflicting precedent at %s** — %s. Resolve "
                           "before answering a third way." %
                           (qk, same[0]["company"],
                            " vs ".join(sorted("%r" % a for a in distinct))))
            elif same:
                own.append("  - `%s` (same employer, %s): %s" %
                           (qk, same[0]["when"], same[0]["answer"]))
            elif rows:
                own.append("  - `%s` (latest, %s at %s): %s" %
                           (qk, rows[0]["when"], rows[0]["company"], rows[0]["answer"]))
        if own:
            L.append("- **Form answers — precedent:**")
            L.extend(own)
        else:
            L.append("- **Form answers — precedent:** none captured yet; record what you "
                     "answer (`form_answers` on the applications[] row) so the next form "
                     "starts from precedent, not from the rule")
        L.append("")

    unt = rep["untriggered"]
    L.append("## Follow-up work your applications created (%d unlinked)" % len(unt))
    L.append("")
    if unt:
        L.append("Each submission below has NO ask, draft or touch naming it as trigger — "
                 "the work it created exists nowhere yet:")
        L.append("")
        for u in unt:
            L.append("- **%s** (`%s`) — application `%s`, %s. Generate the follow-up and "
                     "stamp it `trigger_kind: application`, `trigger_ref: %s`." %
                     (u["title"] or u["opp_id"], u["opp_id"],
                      u["app_id"] or u["date"] or "?", u["status"],
                      u["app_id"] or u["date"] or "?"))
    else:
        L.append("Every submitted application has follow-up work linked to it.")
    L.append("")

    seqs = rep["sequences"]
    unblocked = {k: v for k, v in seqs.items() if v["state"] == "unblocked"}
    L.append("## Sequences unblocked now (%d of %d)" % (len(unblocked), len(seqs)))
    L.append("")
    for sid, s in sorted(seqs.items(),
                         key=lambda kv: 0 if kv[1]["state"] == "unblocked" else 1):
        L.append("- `%s` — **%s**" % (sid, s["state"]))
        for st in s["steps"]:
            L.append("    - step %s: %s (%s)" % (st["step"], st["state"], st["where"]))
    if not seqs:
        L.append("No multi-step sequences are recorded.")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()
    root = profile_root()
    md = render(root)
    if args.stdout:
        print(md)
        return 0
    outdir = os.path.join(root, "views")
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, "applying.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(md)
    print("wrote %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
