#!/usr/bin/env python3
"""
Is the dashboard STALE — does it predate the state it is supposed to show?

WHY THIS EXISTS
---------------
The candidate, 2026-08-03: *"If the daily search ran just after 11am, why did the coordinator not update
the dashboard? Especially since my conversations should have caused it to update. It pushed items
to drafts, but not the dashboard, why?"*

**Because the coordinator had no dashboard step at all.** `generate_dashboard.py` appeared in
`the `jobsearch:daily-run` skill` and `the `jobsearch:weekly-review` skill` — and **zero times** in
`.claude/skills/coordinator/SKILL.md`.

That is the worst possible place for the gap, because the coordinator is the session the candidate actually
works in, and CLAUDE.md's own rule says **"the candidate reads the full text off the dashboard, not the
transcript."** So the one session whose entire output the candidate consumes visually was the one
session that never published. Measured that morning: `drafts.md` was rewritten at 10:58, 11:02,
11:08, 11:13 and 11:14, while `dashboard.html` sat untouched since 10:51 — five rounds of drafting
the candidate could not see.

**Why a script and not a line in the prompt.** The prompts already carried the step and it still
went missing, because the step lived in the runs and the writing happened in the session. A rule
that depends on the right prompt being loaded fails exactly when a different prompt is loaded.
This compares mtimes and does not care who was supposed to remember.

    ⚠️ mtime, not content. If a source is newer than the dashboard, the dashboard cannot be
    showing it. The converse is not proven — a fresh dashboard may still be wrong for other
    reasons, which is why the standing habit is to GREP THE OUTPUT after generating.

## ⭐ THE PUBLISHED VIEW IS A SECOND FRESHNESS DIMENSION (dev #133 / public #22)

Generating the dashboard is not delivering it: the candidate reads a PUBLISHED artifact, and the
publish happens through the Artifact tool — a platform tool only a session can invoke, never a
script. When two sessions race on the same artifact URL the platform refuses the second publish
with a version conflict, and the losing session used to drop it SILENTLY: the repository moved,
the published view did not, and nothing anywhere said so.

No script of ours can republish (only a session holds the Artifact tool), so prevention cannot
ship as code. What ships as code is the guarantee that a dropped publish CANNOT STAY QUIET past
the next check: after a successful publish the session stamps what it published
(`--stamp-published`, a content hash in `.git/` — never committed, like the run lock), and every
later run compares the generated bytes against that stamp. Bytes that differ mean the published
view is behind the repository — dropped publish, forgotten publish, or forgotten stamp, it does
not matter which: **every failure mode converges on the same loud answer, "republish", and
republishing to the same URL is idempotent and cheap.** A false alarm costs one republish; the
old failure cost an unbounded window of the candidate reading a stale dashboard as current. The
asymmetry is the design.

Usage:
    python3 scripts/check_dashboard_fresh.py                    # exit 1 if stale OR publish-behind
    python3 scripts/check_dashboard_fresh.py --fix              # regenerate, then re-check
    python3 scripts/check_dashboard_fresh.py --stamp-published  # AFTER a successful Artifact publish
    python3 scripts/check_dashboard_fresh.py --publish-state    # just the publish dimension

Python 3.9+. Standard library only.
"""

import argparse
import datetime
import hashlib
import json
import os
import subprocess
import sys
import time

import os, sys as _sys
_sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import profile_root as _profile_root
import _tree
ENGINE_SCRIPTS = os.path.dirname(os.path.realpath(__file__))

ROOT = _profile_root()
ARTIFACT = _tree.path(ROOT, "dashboard_artifact")

# ⭐ dev #233 — dashboard.html is a constant TOMBSTONE (the local full copy is retired; a
# stub carries no state, so the two-copies staleness window of public #22 is gone by
# construction). The 2026-08-29 one-artifact collapse then shrank the generated set to the
# SINGLE page below: the router and phase pages are retired (their URLs get moved-stubs
# via pending_stubs.py), so with one page a dropped publish means the phone reader's
# ENTIRE view is stale — this stamp is the only mechanical detector, and it is MORE
# load-bearing than it was over the set, not less. Stamp entries for retired pages in an
# existing stamp file are simply no longer consulted (OUTPUTS drives every comparison),
# so a profile mid-migration can never sit forever-red over a page that no longer exists.
OUTPUTS = [
    _tree.rel("dashboard_artifact"),   # views/ since public #28
]

# Everything the generated set renders. If one of these moved, the set is behind it.
# (focus.md left this list with dev #93 — the generator no longer reads it; asks.jsonl and
# commitments.jsonl are the stores that replaced it. messages.jsonl joined too: channel
# touch derivation reads it, so a new outbound message can change Your Move.
# dev #233 added resume.md + resume_variants.jsonl — the router's presence row reads them —
# and, via SOURCE_DIRS, kb/ and call_preps/: those files rendered on the page since public
# #20 but were NEVER in this list, so a knowledge edit could not make the page stale. A
# freshness gate that skips a source is the missing-reads-as-empty trap wearing mtimes.)
# network.md left SOURCES with the 2026-08-29 collapse: the page no longer renders it
# (D4 — the network is queried, not queued), so its edits cannot change the page.
SOURCES = [
    _tree.rel("drafts"), _tree.rel("cover_letters"),
    _tree.rel("claims"),
    "data/opportunities.jsonl", "data/companies.jsonl", "data/channels.jsonl",
    "data/messages.jsonl", "data/asks.jsonl", "data/commitments.jsonl",
    "data/resume_variants.jsonl",
]
SOURCE_DIRS = [_tree.rel("kb"), _tree.rel("call_preps")]


def mtime(p):
    return os.path.getmtime(p) if os.path.exists(p) else 0


def dir_newest(d):
    """(newest_mtime, name) across the .md files of a source directory; (0, None) if none."""
    best, name = 0, None
    if os.path.isdir(d):
        for n in os.listdir(d):
            if n.endswith(".md"):
                m = mtime(os.path.join(d, n))
                if m > best:
                    best, name = m, n
    return best, name


# ---- the publish stamp (dev #133 / public #22) ----------------------------------------------

def stamp_path():
    """Inside .git so it is never committed (the run-lock precedent); the profile root itself
    if this profile somehow has no .git — still functional, just visible."""
    d = os.path.join(ROOT, ".git")
    return os.path.join(d if os.path.isdir(d) else ROOT, "last_publish.json")


# The stamp file keys each OUTPUTS member by its own path. That shape was introduced when
# the stamp was extended over dev #233's multi-page set (a dropped phase-page publish used
# to hide behind a green dashboard-only stamp) and is KEPT under the one-page collapse:
# it reads legacy single-file stamps and legacy multi-file stamps alike, and it means the
# next page-set change costs a list edit, not a format migration.
def sha_of(path):
    try:
        with open(path, "rb") as fh:
            return hashlib.sha256(fh.read()).hexdigest()
    except OSError:
        return None


def artifact_sha():
    """The primary artifact's own hash — kept as its own name because it also anchors the
    refusal in write_stamp() and the top-level 'nothing generated at all yet' state below."""
    return sha_of(ARTIFACT)


def url_file_for(output_rel):
    """The companion file a publish creates, proving a page has a URL at all — the one
    concrete instance already in the wild is dashboard_artifact.html ->
    dashboard_artifact_url.txt; every OUTPUTS member follows the same '.html' -> '_url.txt'
    transform, in the same directory as the page itself."""
    assert output_rel.endswith(".html"), output_rel
    return _tree.resolve_rel(ROOT, output_rel[:-len(".html")] + "_url.txt")


def read_stamp():
    try:
        with open(stamp_path(), encoding="utf-8") as fh:
            doc = json.load(fh)
    except (OSError, ValueError):
        return None
    if "files" not in doc and "sha256" in doc:
        # Back-compat: a stamp written before this file covered dashboard_artifact.html
        # ALONE, as one {sha256, stamped_at} pair with no "files" key. Read it back as
        # covering just that one entry rather than raising or silently discarding the one
        # real stamp a profile already has.
        doc = {"files": {"dashboard_artifact.html":
                          {"sha256": doc["sha256"], "stamped_at": doc.get("stamped_at")}}}
    return doc


# Since the one-artifact collapse the publish protocol is ONE page, every round —
# stamped unconditionally, exactly as the original single-file stamp always did. The
# machinery below still walks OUTPUTS and still honours the url-file rule (a page with no
# url file is never stamped as published), because that is what keeps a fresh install's
# never-published state benign instead of forever-red.
ALWAYS_PUBLISHED = (_tree.rel("dashboard_artifact"),)


def write_stamp():
    """Record what was just published: the always-published pair unconditionally, plus every
    other OUTPUTS member that already has a url file. Refuses when the primary artifact is
    missing — dashboard_artifact.html's absence means nothing at all could have just been
    published."""
    sha = artifact_sha()
    if sha is None:
        print("⛔ REFUSED — %s does not exist, so nothing can have been published."
              % os.path.basename(ARTIFACT))
        print("  Generate first (generate_dashboard.py), publish with the Artifact tool,")
        print("  THEN stamp. Stamping records a publish; it never substitutes for one.")
        return 1
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    files = {}
    for o in OUTPUTS:
        s = sha_of(_tree.resolve_rel(ROOT, o))
        if s is None:
            continue
        if o not in ALWAYS_PUBLISHED and not os.path.exists(url_file_for(o)):
            continue
        files[o] = {"sha256": s, "stamped_at": now}
    doc = {"files": files,
           "_why": "written after a successful Artifact publish round (dev #133 / public "
                   "#22, extended to the full generated set); check_dashboard_fresh.py "
                   "compares each page's generated bytes against its own entry here"}
    with open(stamp_path(), "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=1)
    print("PUBLISH STAMPED — %d page(s) at %s" % (len(files), now))
    return 0


def _file_publish_state(o, stamp):
    """One OUTPUTS member -> ('current'|'behind'|'unstamped'|'url-missing'|'never-published'|
    'no-artifact', detail_line).

    ⭐ 'url-missing' (added by this dispatch): a stamp EXISTS for this page (it published at
    some point) but its `_url.txt` companion is gone now. This must never fall through to
    'current' (the pre-fix defect — a stale stamp with a matching sha read as current even
    though the bookmark to reach it no longer exists on disk) nor collapse into
    'never-published' (which would route a later reader through "url file absent -> mint a
    new artifact", producing a SECOND artifact at a new URL while the original bookmark, if
    it still resolves on the platform, keeps serving its last snapshot forever — the exact
    dangling-live-URL shape pending_stubs.py exists to eliminate). The url-file check must
    run whenever `entry` exists, not only in the "no entry yet" branch below."""
    sha = sha_of(_tree.resolve_rel(ROOT, o))
    if sha is None:
        return "no-artifact", "%s does not exist yet" % o
    entry = (stamp or {}).get("files", {}).get(o)
    if not entry or not entry.get("sha256"):
        # A page that has NEVER published (no stamp, and no url file — the file the first
        # publish creates) gets an informational pass, not a red it can never clear: the
        # Artifact tool may be legitimately unavailable on this install, and "a gate a user
        # cannot satisfy is not a gate" (coordinator.py #1).
        if not os.path.exists(url_file_for(o)):
            return "never-published", "%s — no stamp, no url file; never published" % o
        return "unstamped", ("%s — the generated page exists but NO publish was ever "
                             "stamped for it" % o)
    # entry exists and has a sha256 — this page WAS published at some point. Check the url
    # file BEFORE comparing content: without the url file there is nothing to recover the
    # published view from regardless of whether the bytes still match.
    if not os.path.exists(url_file_for(o)):
        return "url-missing", (
            "%s — a publish WAS stamped for this page (at %s) but its url file (%s) is now "
            "missing. The artifact URL is NOT lost — recover it via the Artifact tool's "
            "`list` action and write it back to that file. Do NOT mint a new artifact: that "
            "leaves the original URL (if it still resolves) serving its last snapshot "
            "forever while nothing on this profile points at it anymore."
            % (o, entry.get("stamped_at") or "?", os.path.basename(url_file_for(o))))
    if entry["sha256"] != sha:
        return "behind", ("%s DIFFERS from what was last published (stamped %s)"
                          % (o, entry.get("stamped_at") or "?"))
    return "current", "%s matches its last stamp" % o


def publish_state():
    """('current'|'behind'|'unstamped'|'url-missing'|'never-published'|'no-artifact',
    detail lines) — the WORST state across every OUTPUTS member, 'worst' meaning
    'url-missing' first (a stamped page whose bookmark is gone — the fix is recovery, not
    republishing), then 'behind' or 'unstamped' (both mean the same fix: publish, then
    stamp) — the single-file version let a dropped phase-page publish hide behind a green
    dashboard-only stamp; this is the fix. 'url-missing' is the same class of fix (dev/audit
    2026-08-29): a stamped-but-now-file-less page must never silently read as 'current'."""
    sha = artifact_sha()
    if sha is None:
        return "no-artifact", ["no generated artifact yet — the freshness check above is the "
                               "one that gates here"]
    stamp = read_stamp()
    per_file = {o: _file_publish_state(o, stamp) for o in OUTPUTS}
    behind = [o for o, (s, _) in per_file.items() if s == "behind"]
    unstamped = [o for o, (s, _) in per_file.items() if s == "unstamped"]
    url_missing = [o for o, (s, _) in per_file.items() if s == "url-missing"]
    if url_missing or behind or unstamped:
        lines = []
        if url_missing:
            lines.append("state: url-missing — the following page(s) were stamped as "
                         "PUBLISHED but their url file is now MISSING:")
            for o in url_missing:
                lines.append("  - %s" % per_file[o][1])
            lines.append("  RECOVER the URL via the Artifact tool's `list` action — never mint")
            lines.append("  a new artifact for a page that already has one.")
        if behind:
            lines.append("the following page(s) DIFFER from what was last published:")
            for o in behind:
                lines.append("  - %s" % per_file[o][1])
        if unstamped:
            lines.append("the following page(s) exist but NO publish was ever stamped "
                         "for them:")
            for o in unstamped:
                lines.append("  - %s" % per_file[o][1])
        if behind or unstamped:
            lines.append("A publish was dropped (version conflict), skipped, or never stamped —")
            lines.append("all three converge on the same fix: publish each page above with the")
            lines.append("Artifact tool (its own `_url.txt` as `url`; on a conflict: regenerate,")
            lines.append("publish again — NEVER force), then: %s --stamp-published"
                         % os.path.basename(__file__))
        worst = "url-missing" if url_missing else ("behind" if behind else "unstamped")
        return worst, lines
    never = [o for o, (s, _) in per_file.items() if s == "never-published"]
    if len(never) == len(per_file):
        return "never-published", [
            "no publish stamp and no url file for any generated page — this profile has "
            "never published; nothing to compare. The first publish + --stamp-published "
            "arms this check."]
    return "current", ["published view matches the generated bytes for every page that "
                       "has ever been published"]


def stale():
    """[(source, how_many_seconds_newer)] — empty means the generated set is current.
    The set's age is its OLDEST member: one file the generator failed to rewrite means
    the whole set is behind (dev #233 — every output is written on every run)."""
    d = min(mtime(_tree.resolve_rel(ROOT, o)) for o in OUTPUTS)
    if not d:
        return ([(s, 0) for s in SOURCES if os.path.exists(_tree.resolve_rel(ROOT, s))]
                or [("(no generated set yet)", 0)])
    out = []
    for s in SOURCES:
        m = mtime(_tree.resolve_rel(ROOT, s))
        if m > d:
            out.append((s, int(m - d)))
    for sub in SOURCE_DIRS:
        m, name = dir_newest(_tree.resolve_rel(ROOT, sub))
        if m > d:
            out.append(("%s/%s" % (sub, name), int(m - d)))
    return out


def main():
    ap = argparse.ArgumentParser(description="Is the dashboard behind its sources?")
    ap.add_argument("--fix", action="store_true", help="Regenerate, then re-check.")
    ap.add_argument("--stamp-published", action="store_true",
                    help="Record that dashboard_artifact.html was JUST published with the "
                         "Artifact tool. Run it right after every successful publish (dev #133).")
    ap.add_argument("--publish-state", action="store_true",
                    help="Only the publish dimension: is the PUBLISHED view behind the "
                         "generated bytes? Exit 1 if it provably is.")
    args = ap.parse_args()

    if args.stamp_published:
        return write_stamp()

    if args.publish_state:
        state, lines = publish_state()
        if state in ("behind", "unstamped", "url-missing"):
            print("⚠️  PUBLISHED VIEW BEHIND THE REPOSITORY — a publish was dropped or missed.")
            print("=" * 72)
            for l in lines:
                print("  " + l)
            return 1
        print("PUBLISH %s — %s" % (state.upper().replace("-", " "), lines[0]))
        return 0

    bad = stale()
    if args.fix and bad:
        print("Regenerating (%d source(s) newer)..." % len(bad))
        r = subprocess.run([sys.executable, os.path.join(ENGINE_SCRIPTS, "generate_dashboard.py")],
                           capture_output=True, text=True)
        print("  " + (r.stdout.strip().splitlines() or ["?"])[-1])
        if r.returncode:
            print("  !! generate_dashboard.py failed:\n" + r.stderr.strip()[:400])
            return 1
        bad = stale()

    state, plines = publish_state()

    if not bad:
        print("GENERATED SET CURRENT — no source is newer than any generated page.")
        print("  (Freshness is not correctness: still GREP THE OUTPUT for what you added.)")
        if args.fix:
            # --fix is always followed by the publish step in the run prompts, so a pending
            # publish here is the expected NEXT STEP, not a defect — say it, don't gate on it.
            if state in ("behind", "unstamped", "url-missing"):
                print("  NEXT: publish dashboard_artifact.html with the Artifact tool, then")
                print("        %s --stamp-published" % os.path.basename(__file__))
            return 0
        if state in ("behind", "unstamped", "url-missing"):
            print("\n⚠️  BUT THE PUBLISHED VIEW IS BEHIND — %s" % plines[0])
            for l in plines[1:]:
                print("  " + l)
            return 1
        print("  publish: %s" % plines[0])
        return 0

    print("⚠️  DASHBOARD IS STALE — %d source(s) are newer than what was generated." % len(bad))
    print("=" * 72)
    for s, secs in sorted(bad, key=lambda x: -x[1]):
        mins = secs // 60
        print("  %-32s newer by %s" % (s, "%d min" % mins if mins else "%d sec" % secs))
    print("\n  the candidate reads the full text of sendable drafts and letters off the ONE")
    print("  PUBLISHED page (the collapse, 2026-08-29), not the transcript. A stale page means")
    print("  work the candidate cannot see — on 2026-08-03 that was five rounds of drafting unseen.")
    print("\n  Fix:  python3 scripts/check_dashboard_fresh.py --fix")
    print("  Then publish with the Artifact tool, passing views/dashboard_artifact_url.txt as `url`,")
    print("  and stamp the publish:  check_dashboard_fresh.py --stamp-published  (dev #133)")
    return 1


if __name__ == "__main__":
    sys.exit(main())
