#!/usr/bin/env python3
"""Does the published page ACCOUNT FOR every record — and render nothing its window excludes?

⭐ THE TWO-SIDED COVERAGE CONTRACT (dev/audit 2026-09-02, Class C)
-------------------------------------------------------------------
COVERAGE: every record in the row-backed stores is, on the generated page, exactly one of
  * RENDERED    — a row carries `data-rec="<kind>:<id>"`;
  * REMAINDER   — trimmed by a working-set cap into a "+K more" line whose K counts it
                  (`data-more="<set>:<K>"`), so the reader knows it exists and where;
  * TERMINAL    — it has ENDED (a terminal opportunity status, a resolved ask, a commitment
                  whose date has passed) and the page says so by omission.
Anything in none of those is a record the page LOST — silently, which is the shape of the
defect this closes: a renderer's private "closed" set dropped every backlog row (most of
the pipeline on the profile measured) with nothing on the page or in any count to say so.

SCOPE: nothing renders that the window excludes — a terminal opportunity must not appear as
a row, and a call prep renders IN FULL only inside the PREP-OWED horizon.

## Verify the artifact, not the plan (CLAUDE.md trap 6)

`generate_dashboard.py` writes a ledger beside the artifact (`views/dashboard_coverage.json`)
saying where it placed each record. That ledger is a CLAIM. This check reads the STORES for
what exists, the LEDGER for what the renderer believes it did, and the HTML for what is
actually on the page — and fails on any disagreement among the three. It prints
`covered N of M` and refuses to be green when that does not add up (check_engine_purity's
"scanned N of M", copied on purpose).

⚠️ Deliberately SEPARATE from check_dashboard_fresh.py, which is about bytes and stamps —
whether the page is behind its sources or the published view behind the repo. Membership is
a different question with a different remedy, and one check must not grow a second meaning.

## Absence reads as itself

No artifact and no ledger: nothing has been generated yet → `NOT CHECKED`, exit 0 (a new
profile is not nagged). An artifact with NO ledger: generated by a renderer that keeps
none → FAIL, regenerate. A ledger whose window does not name today's date is still checked
against its OWN generation day — staleness is check_dashboard_fresh's dimension.

Usage:
    python3 scripts/check_dashboard_coverage.py            # exit 1 on any gap
    python3 scripts/check_dashboard_coverage.py --verbose  # list every placement

Python 3.9+. Standard library only.
"""

import argparse
import datetime
import html as _html
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import profile_root                                      # noqa: E402
import _tree                                                        # noqa: E402
import knowledge as _kn                                             # noqa: E402
import validate_data as _vd                                         # noqa: E402

LEDGER_NAME = "dashboard_coverage.json"
_REC_RE = re.compile(r'data-rec="([^"]+)"')
_FULL_REC_RE = re.compile(r'data-rec="([^"]+)" data-full="1"')
_MORE_RE = re.compile(r'data-more="([^"]+):(\d+)"')


def _jsonl(root, name):
    path = os.path.join(root, "data", name)
    rows = []
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    rows.append(json.loads(line))
    except OSError:
        pass
    return rows


def expected_records(root):
    """{key: record-ish dict} for every record the contract covers. Preps carry their
    date under 'date' (None when undated)."""
    exp = {}
    for o in _jsonl(root, "opportunities.jsonl"):
        if o.get("id"):
            exp["opp:%s" % o["id"]] = {"kind": "opp", "status": o.get("status")}
    for a in _jsonl(root, "asks.jsonl"):
        if a.get("id"):
            exp["ask:%s" % a["id"]] = {"kind": "ask", "resolved": bool(a.get("resolved_on"))}
    for c in _jsonl(root, "commitments.jsonl"):
        if c.get("id"):
            exp["commit:%s" % c["id"]] = {"kind": "commit", "date": str(c.get("date") or "")}
    d = _tree.path(root, "call_preps")
    if os.path.isdir(d):
        sub = os.path.relpath(d, root)
        for name in sorted(os.listdir(d)):
            if name.endswith(".md") and name.lower() not in _kn.KB_EXEMPT:
                rel = "%s/%s" % (sub, name)
                exp["prep:%s" % rel] = {"kind": "prep", "date": _kn.prep_date(name)}
    return exp


def check(root, verbose=False):
    """(gaps, summary_lines). Empty gaps means the contract holds."""
    html_path = _tree.path(root, "dashboard_artifact")
    ledger_path = os.path.join(root, "views", LEDGER_NAME)
    have_html, have_ledger = os.path.isfile(html_path), os.path.isfile(ledger_path)
    if not have_html and not have_ledger:
        return None, ["NOT CHECKED — no generated dashboard yet (views/dashboard_artifact.html "
                      "absent); run generate_dashboard.py first"]
    if have_html and not have_ledger:
        return ["ARTIFACT WITHOUT A LEDGER — views/%s is missing, so the page was generated "
                "by a renderer that keeps no coverage record; regenerate with the current "
                "generate_dashboard.py" % LEDGER_NAME], []
    try:
        with open(ledger_path, encoding="utf-8") as fh:
            ledger = json.load(fh)
        records = ledger["records"]
        remainders = ledger.get("remainders") or {}
        window = ledger.get("window") or {}
        today = datetime.date.fromisoformat(window["today"])
        horizon = int(window["prep_horizon_days"])
        terminal = set(ledger.get("terminal_statuses") or [])
    except (OSError, ValueError, KeyError, TypeError) as e:
        return ["LEDGER UNREADABLE — views/%s: %s (an unreadable ledger is a gap, never a "
                "pass)" % (LEDGER_NAME, e)], []
    if terminal != set(_vd.TERMINAL_OPP_STATUSES):
        return ["LEDGER VOCABULARY DRIFT — the ledger's terminal set %s is not validate_data's "
                "%s; the page was generated by a renderer with a different vocabulary"
                % (sorted(terminal), sorted(_vd.TERMINAL_OPP_STATUSES))], []
    try:
        with open(html_path, encoding="utf-8") as fh:
            page = fh.read()
    except OSError as e:
        return ["ARTIFACT UNREADABLE — %s" % e], []

    on_page = set(_html.unescape(m) for m in _REC_RE.findall(page))
    full_on_page = set(_html.unescape(m) for m in _FULL_REC_RE.findall(page))
    more_on_page = {}
    for set_name, k in _MORE_RE.findall(page):
        more_on_page[_html.unescape(set_name)] = int(k)

    exp = expected_records(root)
    gaps, placements = [], []
    counts = {"rendered": 0, "remainder": 0, "terminal": 0}
    remainder_members = {}
    for key, meta in sorted(exp.items()):
        entry = records.get(key)
        if not entry:
            gaps.append("UNPLACED — %s is in the store but the page neither rendered it, "
                        "counted it in a remainder, nor marked it terminal" % key)
            continue
        disp, where = entry.get("disposition"), entry.get("where")
        placements.append("%-10s %-24s %s" % (disp, where, key))
        if disp == "rendered":
            counts["rendered"] += 1
            if key not in on_page:
                gaps.append("CLAIMED RENDERED, NOT ON PAGE — %s (ledger says %s)" % (key, where))
        elif disp == "remainder":
            counts["remainder"] += 1
            remainder_members.setdefault(where, []).append(key)
        elif disp == "terminal":
            counts["terminal"] += 1
            k = meta["kind"]
            ok = ((k == "opp" and meta.get("status") in terminal)
                  or (k == "ask" and meta.get("resolved"))
                  or (k == "commit" and _vd.is_date(meta.get("date"))
                      and meta["date"] < today.isoformat()))
            if not ok:
                gaps.append("CLAIMED TERMINAL, NOT TERMINAL — %s (%s) has not ended, so "
                            "omitting it hides a live record" % (key, json.dumps(meta)))
        else:
            gaps.append("UNKNOWN DISPOSITION — %s: %r" % (key, disp))
    # A set's K counts everything it trimmed; a record trimmed here but rendered in another
    # set is RENDERED (the strongest placement wins), so K may exceed the records whose final
    # placement is this remainder — never the reverse. The page's K must equal the ledger's.
    for set_name, members in sorted(remainder_members.items()):
        k_ledger = remainders.get(set_name)
        if k_ledger is None or k_ledger < len(members):
            gaps.append("REMAINDER MISCOUNT — set %s: ledger says +%s more but %d record(s) "
                        "rest on that count" % (set_name, k_ledger, len(members)))
    # Every "+K more" the ledger recorded must be on the page with the same K, and vice
    # versa — whichever side disagrees, the reader is being told a wrong count.
    for set_name in sorted(set(remainders) | set(more_on_page)):
        k_ledger, k_page = remainders.get(set_name), more_on_page.get(set_name)
        if k_page is None:
            gaps.append("REMAINDER NOT ON PAGE — set %s trims %s record(s) but the page has "
                        "no '+K more' line for it" % (set_name, k_ledger))
        elif k_page != k_ledger:
            gaps.append("REMAINDER MISCOUNT ON PAGE — set %s shows +%d more but the ledger "
                        "trimmed %s" % (set_name, k_page, k_ledger))
    # SCOPE — nothing the window excludes.
    limit = today + datetime.timedelta(days=horizon)
    for key in sorted(on_page):
        meta = exp.get(key)
        if meta is None:
            gaps.append("RENDERED, NOT A RECORD — %s is on the page but no such record exists "
                        "(stale render, or a row derived from nothing)" % key)
            continue
        if meta["kind"] == "opp" and meta.get("status") in terminal:
            gaps.append("TERMINAL ROLE RENDERED — %s (status %r) is on the page"
                        % (key, meta.get("status")))
        if meta["kind"] == "prep" and key in full_on_page:
            d = meta.get("date")
            if d is None or d < today or d > limit:
                gaps.append("PREP IN FULL OUTSIDE THE WINDOW — %s (call date %s) renders in "
                            "full; the window is %s..%s" % (key, d, today, limit))
    n_exp = len(exp)
    n_placed = n_exp - sum(1 for g in gaps if g.startswith("UNPLACED"))
    lines = ["covered %d of %d record(s) — %d rendered · %d in counted remainders · "
             "%d terminal (generated %s, prep window %d days)"
             % (n_placed, n_exp, counts["rendered"], counts["remainder"],
                counts["terminal"], today.isoformat(), horizon)]
    if verbose:
        lines.extend("  " + p for p in placements)
    return gaps, lines


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()
    root = profile_root()
    gaps, lines = check(root, verbose=args.verbose)
    print("Dashboard coverage — stores vs ledger vs views/dashboard_artifact.html")
    for l in lines:
        print("  " + l)
    if gaps is None:
        return 0
    if not gaps:
        print("  CLEAN — every record is rendered, counted, or terminal; nothing renders "
              "outside its window")
        return 0
    print("\n" + "=" * 72)
    print("%d GAP(S)" % len(gaps))
    print("=" * 72)
    for g in gaps:
        print("  - " + g)
    print("\n  Remedy: regenerate (generate_dashboard.py) and re-check; a gap that survives a "
          "regeneration is a renderer defect — report it, never hand-edit the page.")
    return 1


if __name__ == "__main__":
    sys.exit(main())
