#!/usr/bin/env python3
"""The conversations working view — what each upcoming call still needs, as a query.

⭐ WHY THIS IS A GENERATED VIEW AND NOT A RULE IN PROSE
-------------------------------------------------------
`conversations/` was the only phase with real data and no capability at all: the schedule
lived in `data/commitments.jsonl`, prep notes lived in three durable stores, and the one
question that joins them — *does this upcoming call have its prep written?* — was answered
by a prose rule in daily-run ("ask whether one already exists before promising") plus the
owner remembering to ask the coordinator by hand before each call. A rule in prose is read
by whoever happens to re-read it; a row in a view is read by every run. So the join is a
QUERY now (the `precondition.py` shape: a named field, a strict parser that refuses what it
cannot read, and a resolver against data that already exists), and daily-run's firing rule
is mechanical: **a `PREP OWED` row inside the horizon is drained this run by invoking the
`call-prep` skill.** The fact makes the firing inevitable; no memory involved.

⭐ ONE EXISTENCE PREDICATE, NEVER TWO (dev #153). "Does prep exist" is answered ONLY by
`knowledge.prep_hits()` — the same resolver behind `knowledge.py --prep-exists`, covering
all three stores (promoted `pipeline/kb/<company_id>.md`, live `conversations/`, archived
`archive/call-preps/`). This module does not grow a second file-existence check; dev #153
is the drift that caused. A partial prep (a records-only note carrying
`**Prep status:** incomplete — <reason>`) does NOT satisfy the predicate: it reports as
`owed-partial`, still owed, so a degraded note can never impersonate a full one.

⚠️ AN UNPARSEABLE VALUE IS REPORTED, NEVER GUESSED. A commitment whose date is the
migration marker `unresolved` (or is unreadable), a row naming no counterparty at all, or a
prep-status field nobody can read — each is a LOUD row in this view and in the counts,
because a precondition nobody can read is worse than none: it looks handled and is not.

⭐ READ-ONLY BY CONSTRUCTION — regenerate after every recorded change, never edit.
The write path is the session recording data (record.py, and `call-prep` writing the note);
the view is where you look. A run that fails to write a prep leaves `PREP OWED` standing
next run — self-healing loudness; nothing depends on the run remembering.

Usage:
    python3 conversations.py             # write <profile>/views/conversations.md
    python3 conversations.py --stdout    # print instead of writing
    python3 conversations.py --json      # machine-readable rows
    python3 conversations.py --days 14 --today 2026-01-05
    python3 conversations.py --check     # exit 1 on any needs-you row (advisory in the run)

Python 3.9+. Standard library only.
"""

import argparse
import datetime
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import profile_root
import knowledge
import trigger

HORIZON_DAYS = 7

# States that must render as NEEDS-YOU — owned here so consumers (generate_dashboard.py,
# daily-run) group by membership instead of re-deriving the set (the precondition.py
# NOT_SENDABLE move). Every member is either work owed or a defect nobody may guess over.
NEEDS_YOU = frozenset({"owed", "owed-partial", "unlinked", "unreadable",
                       "unresolved-date", "unreadable-date"})

# Every state report() emits, in the order the working view reads them.
STATES = ("prepped", "owed", "owed-partial", "unlinked", "unreadable",
          "unresolved-date", "unreadable-date")
# ⭐ A placeable commitment PAST the horizon is one report() deliberately does not row —
# the horizon exists so a run preps the near calls, not the whole quarter. The dashboard's
# week list still renders it (every future commitment, soonest first), so its prep state
# needs a name that says exactly that, owned here beside the states it is not one of
# (public #48, stage 1: a filter value must come from the module that owns the
# vocabulary, never from the renderer).
BEYOND_HORIZON = "beyond-horizon"
PREP_STATES = STATES + (BEYOND_HORIZON,)

# The subset that is genuinely "a prep must be written/finished" — what the firing rule
# drains via `call-prep`. The other loud states need a data fix first, not a note.
OWED = frozenset({"owed", "owed-partial"})

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/conversations.py — DO NOT EDIT. This view is read-only by\n"
    "     construction (D5): every fact on it lives on a record, and an edit here is\n"
    "     overwritten by the next regeneration without notice. Change the record in\n"
    "     session (record.py) and regenerate. -->\n")


def _iso(d):
    try:
        return datetime.date.fromisoformat(str(d))
    except (TypeError, ValueError):
        return None


def _resolve_counterparty(c, opps_by_id, channels_by_id, companies_by_id):
    """(kind, id, display_name) or (None, None, why) when the row cannot say who it is
    with. opp_id wins (a call about a role preps for the COMPANY); channel_id covers a
    call with a recruiting firm (kb/ is per company, so that kind searches notes only)."""
    opp_id = c.get("opp_id")
    if opp_id:
        opp = opps_by_id.get(opp_id)
        if opp is None:
            return None, None, ("opp_id %r resolves to no opportunity (validate_data.py "
                                "flags this too) — fix the link, then re-run" % opp_id)
        cid = opp.get("company_id")
        if not cid:
            return None, None, ("opportunity %r carries no company_id — prep existence "
                                "is resolved per company, so link one" % opp_id)
        name = (companies_by_id.get(cid) or {}).get("name") or cid
        return "company", cid, name
    ch_id = c.get("channel_id")
    if ch_id:
        if ch_id not in channels_by_id:
            return None, None, ("channel_id %r resolves to no channel (validate_data.py "
                                "flags this too) — fix the link, then re-run" % ch_id)
        name = (channels_by_id.get(ch_id) or {}).get("label") or ch_id
        return "channel", ch_id, name
    return None, None, ("no opp_id or channel_id — the schedule row cannot say who the "
                        "meeting is with, so prep existence cannot be resolved; link it "
                        "and re-run")


def report(root, days=HORIZON_DAYS, today=None):
    """One row per commitment that needs placing or prepping. States:

        prepped          a complete prep exists — `preps` lists where
        owed             PREP OWED: nothing in any of the three stores
        owed-partial     PREP OWED: only incomplete (records-only) note(s) — finish in place
        unlinked         the row cannot name its counterparty — a data fix, not a note
        unreadable       a prep-status field nobody can read — loud, never a pass
        unresolved-date  date is the migration marker `unresolved` — cannot be placed
        unreadable-date  date is neither ISO nor `unresolved` — cannot be placed

    Placeable rows outside [today, today+days] are out of scope (the horizon exists so a
    run preps the near calls, not the whole quarter); unplaceable rows ALWAYS report,
    because a meeting nobody can place on a calendar is urgent by construction.
    """
    today = today or datetime.date.today()
    limit = today + datetime.timedelta(days=days)
    opps_by_id = {o.get("id"): o for o in trigger.load_jsonl(root, "opportunities.jsonl")}
    channels_by_id = {c.get("id"): c for c in trigger.load_jsonl(root, "channels.jsonl")}
    companies_by_id = {c.get("id"): c for c in trigger.load_jsonl(root, "companies.jsonl")}

    rows = []
    for c in trigger.load_jsonl(root, "commitments.jsonl"):
        base = {"id": c.get("id"), "date": str(c.get("date") or ""),
                "time": c.get("time") or "", "title": c.get("title") or c.get("id") or "?",
                "who": c.get("who") or "", "kind": None, "counterparty": None,
                "counterparty_name": "", "preps": []}
        raw_date = c.get("date")
        if str(raw_date) == "unresolved":
            rows.append(dict(base, state="unresolved-date",
                             why="date is the migration marker `unresolved` — verify the "
                                 "real date (invite .ics, never recall) and set it on the "
                                 "record"))
            continue
        d = _iso(raw_date)
        if d is None:
            rows.append(dict(base, state="unreadable-date",
                             why="date %r is neither ISO nor the literal `unresolved` — a "
                                 "commitment nobody can place looks handled and is not"
                                 % raw_date))
            continue
        if d < today or d > limit:
            continue
        kind, cid, name_or_why = _resolve_counterparty(
            c, opps_by_id, channels_by_id, companies_by_id)
        if kind is None:
            rows.append(dict(base, state="unlinked", why=name_or_why))
            continue
        base.update(kind=kind, counterparty=cid, counterparty_name=name_or_why)
        hits = knowledge.prep_hits(root, cid, kind)
        base["preps"] = [p for p, _s in hits]
        unreadable = [p for p, s in hits if s == "unreadable"]
        if unreadable:
            rows.append(dict(base, state="unreadable",
                             why="prep-status field nobody can read in %s — fix the "
                                 "`**Prep status:**` line (complete / incomplete — "
                                 "<reason>); until then this prep cannot count as written"
                                 % ", ".join(unreadable)))
        elif any(s == "complete" for _p, s in hits):
            rows.append(dict(base, state="prepped",
                             why="prep exists: %s" % ", ".join(p for p, _s in hits)))
        elif hits:
            rows.append(dict(base, state="owed-partial",
                             why="PREP OWED (partial) — only a records-only incomplete "
                                 "note exists (%s); finish it in place (call-prep), never "
                                 "start a second file" % ", ".join(p for p, _s in hits)))
        else:
            rows.append(dict(base, state="owed",
                             why="PREP OWED — nothing for %s in pipeline/kb/, "
                                 "conversations/, or archive/call-preps/; write "
                                 "conversations/call_prep_<date>.md this run (call-prep)"
                                 % cid))
    rows.sort(key=lambda r: (r["date"], r["time"], str(r["id"])))
    return rows


def render(root, days=HORIZON_DAYS, today=None):
    today = today or datetime.date.today()
    rows = report(root, days=days, today=today)
    placeable = [r for r in rows if not r["state"].endswith("-date")]
    unplaceable = [r for r in rows if r["state"].endswith("-date")]
    n_owed = sum(1 for r in rows if r["state"] in OWED)
    n_loud = sum(1 for r in rows if r["state"] in NEEDS_YOU)

    L = [GENERATED_HEADER,
         "# Conversations — the working view",
         "",
         "_Generated %s. Every commitment in the next %d day(s), each carrying what it "
         "still needs — a `PREP OWED` row is drained by the `call-prep` skill, this run, "
         "never promised for later. Regenerate after every recorded change._"
         % (today.isoformat(), days),
         ""]

    L.append("## Upcoming — next %d day(s) (%d)" % (days, len(placeable)))
    L.append("")
    if not placeable:
        L.append("Nothing scheduled inside the horizon.")
        L.append("")
    for r in placeable:
        when = r["date"] + ((" " + r["time"]) if r["time"] else "")
        L.append("### %s — %s" % (when, r["title"]))
        L.append("")
        if r["who"]:
            L.append("- **Who:** %s" % r["who"])
        if r["counterparty"]:
            L.append("- **Counterparty:** %s (`%s:%s`)"
                     % (r["counterparty_name"], r["kind"], r["counterparty"]))
        if r["state"] == "prepped":
            for p in r["preps"]:
                L.append("- **Prep:** ✅ `%s`" % p)
            L.append("  - Link to it — never re-promise a note that exists (dev #153).")
        else:
            L.append("- **Prep:** ⛔ **%s** — %s" % (r["state"].upper(), r["why"]))
        L.append("- _Meeting time is verified from the invite's `.ics` "
                 "(`parse_ics.py`), never recall._")
        L.append("")

    if unplaceable:
        L.append("## ⛔ Commitments that cannot be placed (%d)" % len(unplaceable))
        L.append("")
        L.append("A meeting nobody can put on a calendar is urgent by construction — fix "
                 "the record, then regenerate:")
        L.append("")
        for r in unplaceable:
            L.append("- **%s** (`%s`) — %s" % (r["title"], r["id"], r["why"]))
        L.append("")

    L.append("## Summary")
    L.append("")
    L.append("- %d commitment(s) in the horizon · %d prep(s) owed · %d row(s) needing "
             "you in total" % (len(placeable), n_owed, n_loud))
    if n_owed:
        L.append("- ⛔ **Every PREP OWED row above is drained THIS RUN (`call-prep`)** — "
                 "a prep that silently does not get written is worse than a loud owed "
                 "row; the row stands until the note exists and is complete.")
    L.append("")
    return "\n".join(L), rows


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stdout", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--days", type=int, default=HORIZON_DAYS)
    ap.add_argument("--today", metavar="YYYY-MM-DD")
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any row needs you (owed, unlinked, unreadable, "
                         "unplaceable). Consumed advisorily by the scheduled run — it "
                         "must drain, not wedge.")
    args = ap.parse_args()

    try:
        today = (datetime.date.fromisoformat(args.today) if args.today else None)
    except ValueError:
        sys.stderr.write("--today must be YYYY-MM-DD\n")
        return 2

    root = profile_root()
    if args.json:
        print(json.dumps(report(root, days=args.days, today=today), indent=1))
        return 0
    md, rows = render(root, days=args.days, today=today)
    if args.stdout:
        print(md)
    else:
        outdir = os.path.join(root, "views")
        os.makedirs(outdir, exist_ok=True)
        path = os.path.join(outdir, "conversations.md")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(md)
        print("wrote %s" % path)

    # The loud tail is not optional decoration: it is how a scheduled session, reading only
    # tool output, cannot miss what the horizon owes. A quiet write would be the
    # missing-reads-as-empty trap applied to this run's own view.
    loud = [r for r in rows if r["state"] in NEEDS_YOU]
    for r in loud:
        print("⛔ %s %s [%s]: %s" % (r["date"], (r["title"] or "?")[:60], r["state"],
                                     r["why"]))
    if loud:
        n_owed = sum(1 for r in loud if r["state"] in OWED)
        if n_owed:
            print("⛔ %d PREP OWED — drain each THIS RUN by invoking the call-prep skill; "
                  "never promise one for a later run." % n_owed)
        print("%d row(s) need you (see views/conversations.md)." % len(loud))
    else:
        print("Every commitment in the horizon is placed and prepped.")

    if args.check:
        return 1 if loud else 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
