#!/usr/bin/env python3
"""handoff_state.py — render the session-handoff letter's "State (from records)" block.

WHY THIS EXISTS (dev #492 / public #81)
---------------------------------------
The handoff letter (`handoff.md`) used to restate pipeline state as PROSE: which decisions were
open, where each opportunity stood, who the way in was. Prose is a second copy, and a second copy
drifts. The reporter watched a letter call a decision open after the action was recorded, and
repeat a relationship path the records had corrected hours earlier. The next session read the
letter as current.

The fix is structural, not editorial. Everything the letter used to say about STATE is a fact the
stores already hold, so this script RENDERS it from the stores, and the letter embeds the output
verbatim. The letter's own prose is then only what the stores cannot hold: reasoning, and next
steps — written against record ids, never restating what the id resolves to.

WHAT IT RENDERS (all of it read from `data/*.jsonl`, nothing from narrative)
  * decisions — every OPEN row of `asks.jsonl` (`your_move.open_asks`, the one definition of
    "open"), and every ask RESOLVED within the last `--window` days with how it resolved, so a
    decision that was taken reads as taken, not as open.
  * each live opportunity (status not terminal) — its current `status`/`stage`/`verdict`, who acts
    next and by when, its relationship path(s) from `involvements.jsonl`, and the newest date any
    of its own records carries.

⭐ REGENERATE, NEVER CARRY OVER. The block is a pure function of the stores: running this again
always yields the current state, so a superseded decision or a corrected path cannot survive a
rewrite of the letter. The skill that writes the letter must re-run this and discard any block
the previous letter held (dev #492). The block is wrapped in BEGIN/END markers so that discarding
is mechanical.

⭐ A relationship path is read THROUGH the people store's `merged_into` chain (graph.Graph
resolves it at read time): an involvement naming an absorbed alias renders as the survivor. Reading
the alias row directly is exactly the stale-field defect this exists to prevent.

LOUD, NEVER EMPTY. An unreadable store line raises and exits 2; a date that is not ISO renders as
`UNREADABLE(<raw>)`; an opportunity with no recorded path says `no path recorded` — a missing
thing must not read as an empty thing. The header always prints the counts it rendered.

Usage:
    ~/.claude/jobsearch/run handoff_state.py                  # the bound profile
    ~/.claude/jobsearch/run handoff_state.py --window 14      # resolved-ask lookback, days
    python3 handoff_state.py --data-dir <dir> --today 2026-01-31   # tests / fixtures

Exit codes: 0 rendered · 2 a store could not be read · 3 no profile bound (nothing rendered).
Read-only: this script writes nothing.

Python 3.9+. Standard library only. No network.
"""
import argparse
import datetime
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import _root  # noqa: E402
import validate_data as _vd  # noqa: E402
import your_move as _ym  # noqa: E402
from graph import Graph  # noqa: E402

BEGIN = "<!-- BEGIN state-from-records (generated by handoff_state.py; do not edit) -->"
END = "<!-- END state-from-records -->"
DEFAULT_WINDOW_DAYS = 14
_ISO = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _date(raw):
    """(sortable-or-None, display) for a stored date. A value that is not ISO is shown, flagged,
    never dropped and never guessed at."""
    if raw is None or raw == "":
        return None, "-"
    if isinstance(raw, str) and _ISO.match(raw):
        try:
            datetime.date.fromisoformat(raw)
            return raw, raw
        except ValueError:
            pass
    return None, "UNREADABLE(%s)" % (raw,)


def _one_line(text):
    return " ".join(str(text or "").split())


def _newest_date(opp, graph_):
    """The newest ISO date any of this opportunity's OWN records carries: its research log, its
    touches, its applications. `None` when it has none — rendered as `-`, not as today."""
    dates = []
    for e in opp.get("research_log") or []:
        if isinstance(e, dict):
            dates.append(e.get("date"))
    for store in ("touches", "applications"):
        for r in graph_.stores.get(store, []):
            if r.get("opp_id") == opp.get("id"):
                dates.append(r.get("date"))
                dates.append(r.get("responded_on"))
    good = [d for d in dates if isinstance(d, str) and _ISO.match(d)]
    return max(good) if good else None


def _path_lines(opp_id, graph_):
    """One line per recorded way in, read from the CURRENT involvement rows with the person
    resolved through any merge (graph.people_for_opportunity). Empty list means NO PATH
    RECORDED, which the caller says out loud."""
    lines = []
    for person, inv in graph_.people_for_opportunity(opp_id):
        lines.append("%s (%s%s) — involvement %s"
                     % (person.get("name") or person.get("id"),
                        inv.get("path_type") or "path type not recorded",
                        ", %s" % inv["role"] if inv.get("role") else "",
                        inv.get("status") or "status not recorded"))
    return sorted(lines)


def _decision_lines(asks, today, window_days):
    open_rows = _ym.open_asks(asks)
    cutoff = (datetime.date.fromisoformat(today)
              - datetime.timedelta(days=window_days)).isoformat()
    resolved = [a for a in asks if a.get("resolved_on")
                and _date(a.get("resolved_on"))[0] is not None
                and a["resolved_on"] >= cutoff]
    resolved.sort(key=lambda a: (a["resolved_on"], str(a.get("id"))), reverse=True)
    out_open = []
    for a in open_rows:
        by = _date(a.get("act_by"))[1]
        out_open.append("- `%s` [%s] OPEN · act by %s%s — %s"
                        % (a.get("id"), a.get("kind"), by,
                           " · opp `%s`" % a["opp_id"] if a.get("opp_id") else "",
                           _one_line(a.get("title"))))
    out_res = []
    for a in resolved:
        out_res.append("- `%s` [%s] RESOLVED %s (%s)%s — %s"
                       % (a.get("id"), a.get("kind"), a["resolved_on"],
                          _one_line(a.get("resolution")) or "no resolution recorded",
                          " · opp `%s`" % a["opp_id"] if a.get("opp_id") else "",
                          _one_line(a.get("title"))))
    return out_open, out_res


def render(data_dir, today=None, window_days=DEFAULT_WINDOW_DAYS):
    """The block, as one string, a pure function of the stores in `data_dir` and `today`."""
    today = today or datetime.date.today().isoformat()
    graph_ = Graph(data_dir)          # raises on an unreadable store line: loud by construction
    asks = graph_.stores["asks"]
    opps = [o for o in graph_.stores["opportunities"]
            if o.get("id") and o.get("status") not in _vd.TERMINAL_OPP_STATUSES]
    opps.sort(key=lambda o: o["id"])
    out_open, out_res = _decision_lines(asks, today, window_days)

    lines = [BEGIN, "## State (from records)", "",
             "Rendered %s from `data/*.jsonl`: %d open decisions, %d resolved in the last %d days, "
             "%d live opportunities. Regenerated with every letter; never carried over."
             % (today, len(out_open), len(out_res), window_days, len(opps)), "",
             "### Decisions", ""]
    lines += out_open or ["- no open decisions in `data/asks.jsonl`"]
    if out_res:
        lines += ["", "Resolved in the last %d days:" % window_days] + out_res
    lines += ["", "### Opportunities", ""]
    if not opps:
        lines.append("- no live opportunities in `data/opportunities.jsonl`")
    for o in opps:
        newest = _newest_date(o, graph_)
        owner_by = _date(o.get("next_action_date"))[1]
        lines.append("- `%s` %s — status %s · stage %s · verdict %s · next: %s by %s · "
                     "latest record %s"
                     % (o["id"], _one_line(o.get("title")), o.get("status"), o.get("stage"),
                        o.get("verdict") or "-", o.get("next_action_owner") or "-", owner_by,
                        newest or "-"))
        paths = _path_lines(o["id"], graph_)
        if paths:
            lines += ["  - path: %s" % p for p in paths]
        else:
            lines.append("  - path: no path recorded")
    lines += ["", END]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--data-dir", help="the profile's data directory (default: the bound profile)")
    ap.add_argument("--today", metavar="YYYY-MM-DD",
                    help="the render date (the clock is a parameter so a test pins it)")
    ap.add_argument("--window", type=int, default=DEFAULT_WINDOW_DAYS,
                    help="how many days back a RESOLVED decision is still shown")
    args = ap.parse_args(argv)
    data_dir = args.data_dir
    if not data_dir:
        root = _root.profile_root()
        if _root.is_unbound(root):
            print("handoff_state: NOT RENDERED — no job-search profile is bound here (no "
                  "CLAUDESEARCH_ROOT, no profile at or above the working directory). Do not "
                  "write the letter's state from memory; say so.", file=sys.stderr)
            return 3
        data_dir = os.path.join(root, "data")
    if args.today and not _date(args.today)[0]:
        print("handoff_state: --today %r is not a YYYY-MM-DD date" % args.today, file=sys.stderr)
        return 2
    try:
        sys.stdout.write(render(data_dir, today=args.today, window_days=args.window))
    except ValueError as exc:            # json.JSONDecodeError is a ValueError
        print("handoff_state: NOT RENDERED — a store under %s could not be read (%s). Do not "
              "write the letter's state from memory; fix the store or report it." % (data_dir, exc),
              file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
