#!/usr/bin/env python3
"""Install ~/.claude/jobsearch/run — a stable launcher for every engine script.

⭐ WHY A LAUNCHER AND NOT A SHELL VARIABLE (2026-08-05).
`${CLAUDE_PLUGIN_ROOT}` is unset inside a Bash tool call, so the skills first resolved the engine
per command:  ENGINE=$(cat ~/.claude/jobsearch/engine_root); python3 "$ENGINE/scripts/x.py"

That works, and it still fails the thing that matters. A fresh-session run proved it: the form is
a COMPOUND command with a QUOTED path, and a permission allowlist cannot match either — so every
script call stopped for approval. **An unattended run that stops for a prompt is a run that does
not happen**, which is the exact failure the allowlist exists to prevent.

A launcher at a fixed path makes each call a single unquoted command with a stable prefix:

    ~/.claude/jobsearch/run validate_data.py
    ~/.claude/jobsearch/run record.py set acme-cto stage screening

One allowlist entry covers all of them, and the engine can move without touching a single skill.
"""
import json
import os
import re
import stat
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import engine_root
from _diag import log_machine as _diag_machine

HOME_DIR = os.path.join(os.path.expanduser("~"), ".claude", "jobsearch")
LAUNCHER = os.path.join(HOME_DIR, "run")

# ⭐⭐ MONOTONIC, embedded IN the template body — read by `_template_generation()` below, off
# WHATEVER body is on disk, not off any Python constant a stale copy might disagree with.
# `heal_if_stale()` refuses to regenerate the launcher when the ON-DISK generation is HIGHER
# than the generation this engine copy would write — see its own docstring for the regression
# this exists to close: comparing only rendered BYTES (df068f5) made an older engine copy read a
# newer launcher as "drifted" and rewrite it backward the moment TEMPLATE next changed for any
# unrelated reason. Bump this integer whenever TEMPLATE's BEHAVIOUR changes; a comment-only edit
# does not need a bump, but when in doubt, bump — the cost of an unnecessary bump is one extra
# heal on machines already current, the cost of a missed one is the downgrade this exists to stop.
TEMPLATE_GENERATION = 2

TEMPLATE = """#!/bin/sh
# TEMPLATE_GENERATION: 2
# GENERATED by scripts/install_launcher.py — do not edit; re-run that script instead.
#
# Runs an engine script by BARE NAME, so callers need no path and no shell variable:
#     ~/.claude/jobsearch/run validate_data.py --flag
#
# The engine location is read from engine_root at call time, so moving or reinstalling the
# plugin needs no change here and no change in any skill.
# ⭐⭐ THE POINTER CANNOT BE TRUSTED, SO IT IS VALIDATED HERE — AT THE POINT OF USE.
#
# The desktop app materialises the plugin PER SESSION under
# .../local-agent-mode-sessions/<id>/.../rpm/plugin_<id>, and any script run from that copy used
# to record it as the durable pointer. It works while the session lives; afterwards EVERY
# scheduled run fails at its first script call, hours later and unattended.
#
# _root.py now refuses to write such a path — but that only helps once the FIXED copy is the one
# running, and an older session copy keeps poisoning the pointer until the app restarts. Guarding
# the write is therefore necessary and NOT sufficient. This launcher is a stable file that every
# run goes through, so validating here works no matter which copy did the writing.
ENGINE_FILE="$HOME/.claude/jobsearch/engine_root"
ENGINE=""
if [ -f "$ENGINE_FILE" ]; then
  ENGINE=$(cat "$ENGINE_FILE")
fi

CACHE="$HOME/.claude/plugins/cache/crinaro-marketplace/jobsearch"

# Reject a session-scoped pointer, and one naming a directory that no longer exists.
case "$ENGINE" in
  */local-agent-mode-sessions/*|*/rpm/plugin_*) ENGINE="" ;;
esac
if [ -n "$ENGINE" ] && [ ! -d "$ENGINE/scripts" ]; then
  ENGINE=""
fi

# ⭐⭐ A POINTER INSIDE THE INSTALL CACHE IS NOT AUTHORITATIVE — THE NEWEST INSTALL IS.
#
# The cache KEEPS every version ever installed. So once the pointer names a specific version
# directory, that directory goes on existing forever, the "directory is gone" check above never
# fires, and THE ENGINE FREEZES AT THAT VERSION: every later release installs correctly and is
# then silently never used. Nothing errors. Runs keep succeeding against old code, which is the
# worst shape a failure can take here.
#
# This stayed hidden while the pointer named a developer's working tree, because a working tree
# always tracks itself. It surfaced the moment the pointer was aimed at the marketplace copy.
#
# A pointer OUTSIDE the cache is left alone: that is someone deliberately running against a
# checkout, and taking that away would remove the only way to test an unreleased change.
case "$ENGINE" in
  "$CACHE"/*) ENGINE="" ;;
esac

# Resolve to the newest COMPLETE installed version, which is stable across sessions.
# ⭐⭐ "COMPLETE" — walk newest to oldest and stop at the first version directory that has BOTH
# scripts/ AND .claude-plugin/plugin.json, never just the single newest name. The installer
# writes a version's files, not one atomic directory swap, so a directory can exist mid-sync;
# checking only the newest name used to mean a version caught mid-install made every run exit 2
# ("No usable engine") even while a perfectly good, complete OLDER install sat one entry down.
if [ -z "$ENGINE" ]; then
  if [ -d "$CACHE" ]; then
    for V in $(ls -1 "$CACHE" 2>/dev/null | grep -E '^[0-9]+\\.[0-9]+\\.[0-9]+$' \\
               | sort -t. -k1,1nr -k2,2nr -k3,3nr); do
      if [ -d "$CACHE/$V/scripts" ] && [ -f "$CACHE/$V/.claude-plugin/plugin.json" ]; then
        ENGINE="$CACHE/$V"
        break
      fi
    done
    if [ -n "$ENGINE" ]; then
      # Repair the pointer for every other reader, and only when it actually moved — a run must
      # not rewrite this file on every call.
      # ⭐⭐ NEITHER OUTCOME IS SILENT ANY MORE. A failed repair used to vanish behind
      # `|| true`, which is the exact shape that left a sandbox-vs-real-machine pointer gap
      # unexplainable: nothing recorded that a write was even ATTEMPTED, let alone that it
      # failed. Recording a SUCCESSFUL repair too is what turns this into a signal doctor.py can
      # read (`_diag.py`'s machine-global log — see its own docstring): one repair is
      # housekeeping (a new version just landed); a repair on EVERY call means something keeps
      # rewriting the pointer backward between calls — a live poisoner, not one-off drift.
      # Best-effort either way: a read-only HOME, or a missing python3, must not break the run.
      if [ "$(cat "$ENGINE_FILE" 2>/dev/null)" != "$ENGINE" ]; then
        if printf '%s' "$ENGINE" > "$ENGINE_FILE" 2>/dev/null; then
          python3 "$ENGINE/scripts/_diag.py" pointer-repair to="$V" 2>/dev/null || true
        else
          python3 "$ENGINE/scripts/_diag.py" pointer-repair-failed to="$V" 2>/dev/null || true
        fi
      fi
    fi
  fi
fi

if [ -z "$ENGINE" ]; then
  echo "No usable engine. $ENGINE_FILE is missing, names a directory that is gone, or points" >&2
  echo "inside a per-session plugin copy, and no installed version was found under" >&2
  echo "\\$HOME/.claude/plugins/cache/crinaro-marketplace/jobsearch." >&2
  echo "Reinstall the plugin, or run install_launcher.py from a checkout." >&2
  exit 2
fi
if [ -z "$1" ]; then
  echo "usage: run <script.py> [args...]" >&2
  exit 2
fi
SCRIPT="$ENGINE/scripts/$1"
shift
if [ ! -f "$SCRIPT" ]; then
  echo "No such engine script: $SCRIPT" >&2
  exit 2
fi
case "$SCRIPT" in
  *.sh) exec /bin/sh "$SCRIPT" "$@" ;;
  *)    exec python3 "$SCRIPT" "$@" ;;
esac
"""


def _install_identity():
    """(marketplace, plugin) this engine is installed under — DERIVED, never assumed.

    The generated launcher's cache fallback used to hardcode `careers-plugins/jobsearch`, so a
    fork registered under any other marketplace name got a launcher whose fallback pointed at a
    cache directory that would never exist: the pointer was the only leg it had, and the first
    stale pointer killed every run. Two derivations, in order:

    1. Installed from the cache: the engine path itself is
       ~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/ — read the two segments.
    2. Installed from a checkout: <repo>/plugins/<plugin>/ — the plugin name is the directory,
       and the repo's own catalog (.claude-plugin/marketplace.json `name`) names the
       registration. Falls back to today's names, which keeps every existing install identical.

    ⭐ BOTH SIDES OF THE `relpath` CALL MUST BE REALPATH'D, OR THIS SILENTLY TAKES THE WRONG
    BRANCH. `engine_root()` already resolves through symlinks (its own docstring: realpath, not
    abspath). `$HOME` did not, and on macOS `tempfile.mkdtemp()` (and therefore any HOME pointed
    at a temp dir, which is exactly what the test suite and a CI runner do) sits under
    `/var/folders/...`, a symlink to `/private/var/folders/...`. `relpath` between a resolved and
    an unresolved path shares no prefix, so it returns a long `../..` chain that fails the
    `not rel.startswith(os.pardir)` check — the cache branch is silently skipped, and case 2
    reads `os.path.basename(eng)`, which is the VERSION directory, not `jobsearch`. Caught by
    `TestLauncherSelfHeal.test_migrate_hook_end_to_end_heals_the_launcher`, which failed with a
    launcher naming `cache/crinaro-marketplace/9.9.2` — the version number standing in for the
    plugin name — the day this function grew its first real caller of the derived identity.
    """
    eng = os.path.abspath(engine_root())
    cache_root = os.path.realpath(os.path.join(os.path.expanduser("~"), ".claude", "plugins",
                                               "cache"))
    try:
        rel = os.path.relpath(eng, cache_root)
    except ValueError:  # Windows: paths on different drives
        rel = os.pardir
    if not rel.startswith(os.pardir):
        parts = rel.split(os.sep)  # <marketplace>/<plugin>/<version>/...
        if len(parts) >= 2:
            return parts[0], parts[1]
    plugin = os.path.basename(eng.rstrip(os.sep)) or "jobsearch"
    catalog = os.path.join(os.path.dirname(os.path.dirname(eng)),
                           ".claude-plugin", "marketplace.json")
    try:
        with open(catalog, encoding="utf-8") as fh:
            name = (json.load(fh).get("name") or "").strip()
    except (OSError, ValueError):
        name = ""
    return (name or "crinaro-marketplace"), plugin


def _rendered_template(marketplace, plugin):
    """The exact bytes `install()` writes for this (marketplace, plugin) identity.

    ⭐ SINGLE SOURCE OF TRUTH, shared with `heal_if_stale()`. The two used to compute this
    independently — `install()` inline, `heal_if_stale()` as a name-only substring test — and
    the second one drifted from the first the moment TEMPLATE grew a behavioural fix (the
    cache-freeze rejection block, dev #199-adjacent) that touched no marketplace or plugin name.
    A launcher generated before that fix still contains the current name in full, so the old
    substring test read it as `healthy` and never regenerated it — the exact shape of dev #199's
    own lesson (classify by what a thing DOES, not by what it is called), recurring one level
    down. Rendering here and comparing full bytes in `heal_if_stale()` catches ANY drift from
    today's TEMPLATE, not just a renamed identity.
    """
    body = TEMPLATE
    if (marketplace, plugin) != ("crinaro-marketplace", "jobsearch"):
        body = body.replace("crinaro-marketplace/jobsearch", "%s/%s" % (marketplace, plugin))
    return body


_GENERATION_RE = re.compile(r"^# TEMPLATE_GENERATION: (\d+)$", re.MULTILINE)


def _template_generation(body):
    """The `# TEMPLATE_GENERATION: N` a launcher BODY carries, or None when it has none — a
    launcher generated before this concept existed at all (backward compatible: absence is
    treated as "older than anything", never as "unknown, so refuse")."""
    m = _GENERATION_RE.search(body or "")
    return int(m.group(1)) if m else None


def install():
    os.makedirs(HOME_DIR, exist_ok=True)
    # TEMPLATE carries the default identity so it stays testable as-is; a non-default
    # marketplace or plugin name is substituted at install time (it appears in the CACHE
    # variable and in the no-engine error message — both must move together).
    marketplace, plugin = _install_identity()
    body = _rendered_template(marketplace, plugin)
    with open(LAUNCHER, "w", encoding="utf-8") as fh:
        fh.write(body)
    os.chmod(LAUNCHER, os.stat(LAUNCHER).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    # Ensure the pointer the launcher reads actually exists.
    ptr = os.path.join(HOME_DIR, "engine_root")
    with open(ptr, "w", encoding="utf-8") as fh:
        fh.write(engine_root())
    return LAUNCHER


def heal_if_stale(apply_it=True):
    """Regenerate `~/.claude/jobsearch/run` when it already exists but its BODY has drifted
    from what `install()` would write today — a stale marketplace identity (the original case:
    identifier rename) or any other change to TEMPLATE the launcher predates.

    ⭐ SAME SHAPE AS `heal_install.py` (adr-014): install-machinery self-heal, not a profile
    migration — it runs from `migrate.py`'s own SessionStart hook regardless of whether a
    profile is even present, because a stale generated launcher is a property of the MACHINE,
    not of any one profile.

    A marketplace rename moves the cache path an installed copy actually sits at — the
    generated launcher's `CACHE=".../cache/<marketplace>/jobsearch"` fallback line was
    substituted at the time `install()` last ran, and stays frozen at whatever identity was
    current then. `_root.py`'s `ENGINE_POINTER` already self-heals on every script import
    (`_remember_engine`, structural since dev #199), so the launcher keeps working as long as
    the pointer is valid — but the pointer itself is validated and can be rejected (a vanished
    directory, a session-scoped copy), at which point the launcher falls back to its own baked
    CACHE line. A launcher naming the OLD marketplace segment then finds nothing there and the
    run fails with "No usable engine", even though a perfectly good install exists one path
    segment over. Regenerating the launcher whenever it exists and disagrees with the
    CURRENTLY-DERIVED identity closes that gap.

    ⚠️ THE PREDICATE COMPARES THE FULL RENDERED BODY, NOT A NAME SUBSTRING. It used to test only
    `"cache/%s/%s" % (marketplace, plugin) in body` — which stays true forever once the name is
    right, even when TEMPLATE has since changed underneath it for an unrelated reason. That is
    exactly what happened to the version-freeze fix (the `"$CACHE"/*` rejection block that makes
    a pointer inside the install cache advisory rather than authoritative, so an old install
    doesn't silently freeze the engine at whatever version the pointer happened to name): a
    launcher generated before that fix, but AFTER any marketplace rename, already contains the
    current name in full — the old substring test read it as `healthy` and never regenerated it,
    leaving that launcher permanently unable to resolve past a stale in-cache pointer. Comparing
    against `_rendered_template()` byte-for-byte catches that drift and any future one, because
    it asks "would `install()` write something different?" rather than "does the name look ok?".

    ⭐ ONLY ACTS ON AN EXISTING LAUNCHER. A user who never ran `install_launcher.py` (or
    onboarding) gets nothing created here — creating one from nothing stays onboarding's job,
    the same boundary `heal_install.py` draws around installs it did not create.

    SAFE by this module's own rule (migrate.py's docstring): `install()` overwrites a file
    whose own header says "GENERATED ... do not edit; re-run that script instead" — idempotent,
    reversible (re-running install() again is always safe), and carries no user data.

    ⛔⛔ THE GENERATION GUARD — the fix for a regression shipped in 0.33.0 (df068f5), found
    before TEMPLATE next changed but designed to survive the moment it does. This function
    executes as PART OF whichever engine copy imported it, and `migrate.py --hook` runs from the
    session's OWN copy — which is not necessarily the newest installed one. Comparing full
    rendered bytes (the fix this docstring used to describe as the whole story) closes the
    name-substring gap, but opens a worse one: a session running an OLDER engine copy has an
    OLDER `TEMPLATE`, so a launcher a NEWER copy already wrote correctly reads as "drifted" from
    the old copy's point of view — and it would happily rewrite the newer launcher back to
    yesterday's TEMPLATE. Every call to `run` after that regenerates the CURRENT (correct)
    launcher right back into the STALE one, for as long as anything imports the old copy. This
    is inert only because TEMPLATE has not changed again since 0.33.0 shipped — it activates the
    moment it does.

    So: TEMPLATE carries a monotonic `# TEMPLATE_GENERATION: N` header (`_template_generation()`,
    parsed off whatever body is on disk — never off a Python constant a stale copy might
    disagree with). heal_if_stale regenerates only when the ON-DISK generation is **at or below**
    this copy's own; finding a **strictly higher** on-disk generation means a newer copy already
    wrote it, so this refuses outright and records a `stale-copy-session` machine event (never a
    profile one — dev #151) naming both generations. That event is ALSO the detector this
    project otherwise lacks entirely for "a session is running a stale copy": nothing else
    observes it happening. `doctor.py`'s pointer section and `binding.py --assert` both surface
    it. A launcher with no generation marker at all (written before this concept existed) reads
    as older than anything and is healed normally — the guard only ever refuses a STRICTLY newer
    disk generation, never an absent one.

    Returns (verdict, lines). verdict: absent | healthy | healed | would-heal | refused-stale-copy
    | error. Never raises — callers still wrap this in their own envelope, but it stays
    self-contained so it can be tested and called directly.
    """
    if not os.path.exists(LAUNCHER):
        return "absent", []
    try:
        marketplace, plugin = _install_identity()
    except Exception as e:                      # noqa: BLE001 — fails open, deliberately
        return "error", ["  ⚠️ could not derive the current install identity (%s: %s) — "
                         "launcher left unchanged." % (type(e).__name__, e)]
    expected = _rendered_template(marketplace, plugin)
    try:
        with open(LAUNCHER, encoding="utf-8") as fh:
            body = fh.read()
    except OSError as e:
        return "error", ["  ⚠️ could not read %s (%s) — launcher left unchanged." % (LAUNCHER, e)]
    if body == expected:
        return "healthy", []
    disk_gen = _template_generation(body)
    own_gen = _template_generation(TEMPLATE)
    if disk_gen is not None and own_gen is not None and disk_gen > own_gen:
        _diag_machine("stale-copy-session", own_generation=own_gen, disk_generation=disk_gen)
        return "refused-stale-copy", [
            "  ⛔ %s already carries a NEWER template (generation %d) than this engine's own "
            "TEMPLATE (generation %d) — refusing to regenerate it backward." % (
                LAUNCHER, disk_gen, own_gen),
            "     This session is itself running an OLDER installed copy of jobsearch; a newer "
            "copy already updated the launcher. Recorded as a stale-copy-session event — see "
            "`doctor.py` or `binding.py --assert` on this machine."]
    want = "cache/%s/%s" % (marketplace, plugin)
    reason = ("a cache path (not %s) that no longer matches this install, likely left over "
              "from a marketplace rename" % want) if want not in body else (
              "the current install identity, but its generated body has drifted from what "
              "this engine version writes today")
    if not apply_it:
        return "would-heal", [
            "  would regenerate %s — it names %s." % (LAUNCHER, reason)]
    install()
    return "healed", [
        "  ✅ %s regenerated for the current install — it was naming %s." % (LAUNCHER, reason)]


if __name__ == "__main__":
    print("Installed %s" % install())
    print("Engine    %s" % engine_root())
    print()
    print("Allowlist this one entry to keep unattended runs from prompting:")
    print('    Bash(~/.claude/jobsearch/run:*)')
