#!/usr/bin/env python3
"""Install ~/.claude/jobsearch/run — a stable launcher for every engine script.

⭐ WHY A LAUNCHER AND NOT A SHELL VARIABLE (2026-08-05).
`${CLAUDE_PLUGIN_ROOT}` is unset inside a Bash tool call, so the skills first resolved the engine
per command:  ENGINE=$(cat ~/.claude/jobsearch/engine_root); python3 "$ENGINE/scripts/x.py"

That works, and it still fails the thing that matters. A fresh-session run proved it: the form is
a COMPOUND command with a QUOTED path, and a permission allowlist cannot match either — so every
script call stopped for approval. **An unattended run that stops for a prompt is a run that does
not happen**, which is the exact failure the allowlist exists to prevent.

A launcher at a fixed path makes each call a single unquoted command with a stable prefix:

    ~/.claude/jobsearch/run validate_data.py
    ~/.claude/jobsearch/run record.py set acme-cto stage screening

One allowlist entry covers all of them, and the engine can move without touching a single skill.
"""
import json
import os
import re
import stat
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _root import engine_root
from _diag import log_machine as _diag_machine

HOME_DIR = os.path.join(os.path.expanduser("~"), ".claude", "jobsearch")
LAUNCHER = os.path.join(HOME_DIR, "run")

# ⭐⭐ MONOTONIC, embedded IN the template body — read by `_template_generation()` below, off
# WHATEVER body is on disk, not off any Python constant a stale copy might disagree with.
# `heal_if_stale()` refuses to regenerate the launcher when the ON-DISK generation is HIGHER
# than the generation this engine copy would write — see its own docstring for the regression
# this exists to close: comparing only rendered BYTES (df068f5) made an older engine copy read a
# newer launcher as "drifted" and rewrite it backward the moment TEMPLATE next changed for any
# unrelated reason. Bump this integer whenever TEMPLATE's BEHAVIOUR changes; a comment-only edit
# does not need a bump, but when in doubt, bump — the cost of an unnecessary bump is one extra
# heal on machines already current, the cost of a missed one is the downgrade this exists to stop.
TEMPLATE_GENERATION = 3

TEMPLATE = """#!/bin/sh
# TEMPLATE_GENERATION: 3
# GENERATED by scripts/install_launcher.py — do not edit; re-run that script instead.
#
# Runs an engine script by BARE NAME, so callers need no path and no shell variable:
#     ~/.claude/jobsearch/run validate_data.py --flag
#     ~/.claude/jobsearch/run --where            # print the resolved engine root; exit 0
#
# ⭐⭐ GENERATION 3 (dev #167, closing #249): THE POINTER IS DEMOTED, NOT DEFENDED.
#
# Generations 1 and 2 read `engine_root` first and guarded it at the point of use — reject a
# per-session copy (gen 1), reject an in-cache version pin (gen 2). Each guard was a patch on
# the same symptom: ANY import of an engine script used to write that file, so every writer
# not carrying the newest guard was a fresh poisoning route. One was live the day gen 3 was
# designed: a maintainer tool's temp-directory path is out-of-cache with a scripts/ dir, so
# gen 2 HONORED it. A third guard would have been the third patch on the same symptom.
#
# So generation 3 stops reading `engine_root` for resolution entirely:
#   1. `engine_root.override` — written ONLY by an explicit install_launcher.py run: the one
#      deliberate way to run against a checkout. Honored when it names a directory with a
#      scripts/ dir; otherwise ignored.
#   2. Otherwise: the newest COMPLETE installed version in the cache. "COMPLETE" — walk
#      newest to oldest and stop at the first version directory that has BOTH scripts/ AND
#      .claude-plugin/plugin.json, never just the single newest name: the installer writes a
#      version's files, not one atomic directory swap, so a directory can exist mid-sync,
#      and checking only the newest name used to exit 2 while a complete OLDER install sat
#      one entry down.
#
# `engine_root` is still REPAIRED after resolution — some legacy readers open the FILE — but
# nothing resolves through it any more, so an unpatched writer's scribble influences nothing.
OVERRIDE_FILE="$HOME/.claude/jobsearch/engine_root.override"
LEGACY_FILE="$HOME/.claude/jobsearch/engine_root"
CACHE="$HOME/.claude/plugins/cache/crinaro-marketplace/jobsearch"

ENGINE=""
if [ -f "$OVERRIDE_FILE" ]; then
  ENGINE=$(cat "$OVERRIDE_FILE")
  if [ -z "$ENGINE" ] || [ ! -d "$ENGINE/scripts" ]; then
    ENGINE=""
  fi
fi

if [ -z "$ENGINE" ] && [ -d "$CACHE" ]; then
  for V in $(ls -1 "$CACHE" 2>/dev/null | grep -E '^[0-9]+\\.[0-9]+\\.[0-9]+$' \\
             | sort -t. -k1,1nr -k2,2nr -k3,3nr); do
    if [ -d "$CACHE/$V/scripts" ] && [ -f "$CACHE/$V/.claude-plugin/plugin.json" ]; then
      ENGINE="$CACHE/$V"
      break
    fi
  done
fi

if [ -z "$ENGINE" ]; then
  echo "No usable engine. $OVERRIDE_FILE does not name a live checkout, and no complete" >&2
  echo "installed version was found under" >&2
  echo "\\$HOME/.claude/plugins/cache/crinaro-marketplace/jobsearch." >&2
  echo "Reinstall the plugin, or run install_launcher.py from a checkout." >&2
  exit 2
fi

# Repair the legacy pointer for readers that still open the FILE — informational only, and
# only when it actually moved: a run must not rewrite this file on every call.
# ⭐⭐ NEITHER OUTCOME IS SILENT. A failed repair used to vanish behind `|| true`, which left a
# sandbox-vs-real-machine pointer gap unexplainable. Recording SUCCESSFUL repairs too is what
# turns this into a signal doctor.py can read: one repair is housekeeping; a repair on EVERY
# call means something keeps rewriting the file between calls — a live writer, not drift.
# `from=` classifies the stale value, so the telemetry NAMES the writer without any old code
# cooperating: cache:<version> is a stale session's pinned copy, temp is tooling that ran from
# a temp directory, session is a per-session plugin copy.
# Best-effort either way: a read-only HOME, or a missing python3, must not break the run.
OLD=$(cat "$LEGACY_FILE" 2>/dev/null)
if [ "$OLD" != "$ENGINE" ]; then
  case "$OLD" in
    "") FROM="absent" ;;
    */local-agent-mode-sessions/*|*/rpm/plugin_*) FROM="session" ;;
    "$CACHE"/*) REST="${OLD#"$CACHE"/}"; FROM="cache:${REST%%/*}" ;;
    /tmp/*|/private/tmp/*|/var/folders/*|/private/var/folders/*|*/Temp/*|*/tmp/*) FROM="temp" ;;
    *) FROM="other" ;;
  esac
  if printf '%s' "$ENGINE" > "$LEGACY_FILE" 2>/dev/null; then
    python3 "$ENGINE/scripts/_diag.py" pointer-repair to="$(basename "$ENGINE")" \\
            from="$FROM" 2>/dev/null || true
  else
    python3 "$ENGINE/scripts/_diag.py" pointer-repair-failed to="$(basename "$ENGINE")" \\
            from="$FROM" 2>/dev/null || true
  fi
fi

# `--where` — the resolved engine root as DATA, for callers that need the path itself (the
# scheduled-task fallback line composes it into CLAUDE_PLUGIN_ROOT). This replaces reading the
# legacy pointer file: the answer comes from the SAME resolution every run uses, so the two
# can never disagree.
if [ "$1" = "--where" ]; then
  printf '%s\\n' "$ENGINE"
  exit 0
fi
if [ -z "$1" ]; then
  echo "usage: run <script.py> [args...]   |   run --where" >&2
  exit 2
fi
SCRIPT="$ENGINE/scripts/$1"
shift
if [ ! -f "$SCRIPT" ]; then
  echo "No such engine script: $SCRIPT" >&2
  exit 2
fi
case "$SCRIPT" in
  *.sh) exec /bin/sh "$SCRIPT" "$@" ;;
  *)    exec python3 "$SCRIPT" "$@" ;;
esac
"""


def _install_identity():
    """(marketplace, plugin) this engine is installed under — DERIVED, never assumed.

    The generated launcher's cache fallback used to hardcode `careers-plugins/jobsearch`, so a
    fork registered under any other marketplace name got a launcher whose fallback pointed at a
    cache directory that would never exist: the pointer was the only leg it had, and the first
    stale pointer killed every run. Two derivations, in order:

    1. Installed from the cache: the engine path itself is
       ~/.claude/plugins/cache/<marketplace>/<plugin>/<version>/ — read the two segments.
    2. Installed from a checkout: <repo>/plugins/<plugin>/ — the plugin name is the directory,
       and the repo's own catalog (.claude-plugin/marketplace.json `name`) names the
       registration. Falls back to today's names, which keeps every existing install identical.

    ⭐ BOTH SIDES OF THE `relpath` CALL MUST BE REALPATH'D, OR THIS SILENTLY TAKES THE WRONG
    BRANCH. `engine_root()` already resolves through symlinks (its own docstring: realpath, not
    abspath). `$HOME` did not, and on macOS `tempfile.mkdtemp()` (and therefore any HOME pointed
    at a temp dir, which is exactly what the test suite and a CI runner do) sits under
    `/var/folders/...`, a symlink to `/private/var/folders/...`. `relpath` between a resolved and
    an unresolved path shares no prefix, so it returns a long `../..` chain that fails the
    `not rel.startswith(os.pardir)` check — the cache branch is silently skipped, and case 2
    reads `os.path.basename(eng)`, which is the VERSION directory, not `jobsearch`. Caught by
    `TestLauncherSelfHeal.test_migrate_hook_end_to_end_heals_the_launcher`, which failed with a
    launcher naming `cache/crinaro-marketplace/9.9.2` — the version number standing in for the
    plugin name — the day this function grew its first real caller of the derived identity.
    """
    eng = os.path.abspath(engine_root())
    cache_root = os.path.realpath(os.path.join(os.path.expanduser("~"), ".claude", "plugins",
                                               "cache"))
    try:
        rel = os.path.relpath(eng, cache_root)
    except ValueError:  # Windows: paths on different drives
        rel = os.pardir
    if not rel.startswith(os.pardir):
        parts = rel.split(os.sep)  # <marketplace>/<plugin>/<version>/...
        if len(parts) >= 2:
            return parts[0], parts[1]
    plugin = os.path.basename(eng.rstrip(os.sep)) or "jobsearch"
    catalog = os.path.join(os.path.dirname(os.path.dirname(eng)),
                           ".claude-plugin", "marketplace.json")
    try:
        with open(catalog, encoding="utf-8") as fh:
            name = (json.load(fh).get("name") or "").strip()
    except (OSError, ValueError):
        name = ""
    return (name or "crinaro-marketplace"), plugin


def _rendered_template(marketplace, plugin):
    """The exact bytes `install()` writes for this (marketplace, plugin) identity.

    ⭐ SINGLE SOURCE OF TRUTH, shared with `heal_if_stale()`. The two used to compute this
    independently — `install()` inline, `heal_if_stale()` as a name-only substring test — and
    the second one drifted from the first the moment TEMPLATE grew a behavioural fix (the
    cache-freeze rejection block, dev #199-adjacent) that touched no marketplace or plugin name.
    A launcher generated before that fix still contains the current name in full, so the old
    substring test read it as `healthy` and never regenerated it — the exact shape of dev #199's
    own lesson (classify by what a thing DOES, not by what it is called), recurring one level
    down. Rendering here and comparing full bytes in `heal_if_stale()` catches ANY drift from
    today's TEMPLATE, not just a renamed identity.
    """
    body = TEMPLATE
    if (marketplace, plugin) != ("crinaro-marketplace", "jobsearch"):
        body = body.replace("crinaro-marketplace/jobsearch", "%s/%s" % (marketplace, plugin))
    return body


_GENERATION_RE = re.compile(r"^# TEMPLATE_GENERATION: (\d+)$", re.MULTILINE)


def _template_generation(body):
    """The `# TEMPLATE_GENERATION: N` a launcher BODY carries, or None when it has none — a
    launcher generated before this concept existed at all (backward compatible: absence is
    treated as "older than anything", never as "unknown, so refuse")."""
    m = _GENERATION_RE.search(body or "")
    return int(m.group(1)) if m else None


def install():
    os.makedirs(HOME_DIR, exist_ok=True)
    # TEMPLATE carries the default identity so it stays testable as-is; a non-default
    # marketplace or plugin name is substituted at install time (it appears in the CACHE
    # variable and in the no-engine error message — both must move together).
    marketplace, plugin = _install_identity()
    body = _rendered_template(marketplace, plugin)
    with open(LAUNCHER, "w", encoding="utf-8") as fh:
        fh.write(body)
    os.chmod(LAUNCHER, os.stat(LAUNCHER).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    # The LEGACY pointer, kept current for anything that still opens the file. Since
    # TEMPLATE_GENERATION 3 nothing resolves through it — the launcher resolves newest-complete
    # from the cache (or `engine_root.override`) and repairs this file after resolution. The
    # override is deliberately NOT written here: install() is also called by heal_if_stale()
    # from a SessionStart hook, and a heal must never pin or unpin a checkout as a side effect.
    # See record_deliberate_override(), which only __main__ calls.
    ptr = os.path.join(HOME_DIR, "engine_root")
    with open(ptr, "w", encoding="utf-8") as fh:
        fh.write(engine_root())
    return LAUNCHER


def _override_path():
    """`~/.claude/jobsearch/engine_root.override` — resolved at CALL time off HOME_DIR, so a
    test's monkeypatched HOME_DIR reaches it."""
    return os.path.join(HOME_DIR, "engine_root.override")


def record_deliberate_override(argv=None):
    """The ONE deliberate act that may aim the resolver at a checkout (TEMPLATE_GENERATION 3,
    dev #167 / #249: the pointer is demoted, not defended).

    Generations 1 and 2 let ANY import of an engine script write `engine_root`, then stacked
    guards on the read side — and every writer not carrying the newest guard stayed a live
    poisoning route (a maintainer tool's temp-dir path was honored by gen 2 the day gen 3 was
    designed: out-of-cache, existing directory, scripts/ present). Generation 3's launcher
    reads exactly one override file, `engine_root.override`, and ONLY this function writes it —
    running a script can no longer aim anything anywhere.

    Called from __main__ only — never from install(), never from heal_if_stale() — so a
    SessionStart heal cannot pin or unpin a checkout as a side effect. Outcomes:

      - engine is an INSTALLED cache copy  -> any override is CLEARED. An explicit run from
        the installed copy means "use the standard install"; and writing an override naming a
        cache version would recreate the exact version-freeze gen 2 exists to prevent.
      - engine is EPHEMERAL (temp dir, per-session copy) -> REFUSED: the override would die
        with its directory, and the failure would land hours later in an unattended run.
      - engine is a durable checkout -> the override is WRITTEN. This is the only way it
        comes to exist.

    Every outcome logs a machine event carrying argv, so the write side is never anonymous —
    the read-side twin is the launcher repair event's `from=` classification. Returns
    (verdict, lines); verdict: set | cleared | none | refused-ephemeral.
    """
    import _root
    ov = _override_path()
    arg_note = ":".join(["install_launcher.py"] + list(argv or []))
    eng = engine_root()
    if _root.is_installed_engine(eng):
        if os.path.exists(ov):
            os.remove(ov)
            _diag_machine("launcher-override", action="cleared", argv=arg_note)
            return "cleared", [
                "Override  cleared (%s) — this run came from the installed copy, so "
                "resolution returns to newest-complete in the install cache." % ov]
        _diag_machine("launcher-override", action="none", argv=arg_note)
        return "none", []
    if _root.is_ephemeral_engine(eng):
        _diag_machine("launcher-override", action="refused-ephemeral", argv=arg_note)
        return "refused-ephemeral", [
            "Override  NOT written: %s is ephemeral (a temp directory or a per-session plugin "
            "copy) and would strand every later run when it vanishes — the failure would land "
            "hours later, unattended. Run install_launcher.py from a durable checkout to pin "
            "one." % eng]
    with open(ov, "w", encoding="utf-8") as fh:
        fh.write(eng)
    _diag_machine("launcher-override", action="set", argv=arg_note)
    return "set", [
        "Override  %s -> %s" % (ov, eng),
        "          Every `run` call now resolves THIS checkout. Re-run install_launcher.py "
        "from the installed copy (or delete the override file) to return to newest-complete "
        "resolution."]


def heal_if_stale(apply_it=True):
    """Regenerate `~/.claude/jobsearch/run` when it already exists but its BODY has drifted
    from what `install()` would write today — a stale marketplace identity (the original case:
    identifier rename) or any other change to TEMPLATE the launcher predates.

    ⭐ SAME SHAPE AS `heal_install.py` (adr-014): install-machinery self-heal, not a profile
    migration — it runs from `migrate.py`'s own SessionStart hook regardless of whether a
    profile is even present, because a stale generated launcher is a property of the MACHINE,
    not of any one profile.

    A marketplace rename moves the cache path an installed copy actually sits at — the
    generated launcher's `CACHE=".../cache/<marketplace>/jobsearch"` line was substituted at
    the time `install()` last ran, and stays frozen at whatever identity was current then.
    Since TEMPLATE_GENERATION 3 that baked CACHE line is the launcher's PRIMARY resolution
    (the legacy `engine_root` pointer is informational and never read for resolution; only an
    explicit `engine_root.override` outranks the cache walk) — so a launcher naming the OLD
    marketplace segment finds nothing there and the run fails with "No usable engine", even
    though a perfectly good install exists one path segment over. Regenerating the launcher
    whenever it exists and disagrees with the CURRENTLY-DERIVED identity closes that gap.

    ⚠️ THE PREDICATE COMPARES THE FULL RENDERED BODY, NOT A NAME SUBSTRING. It used to test only
    `"cache/%s/%s" % (marketplace, plugin) in body` — which stays true forever once the name is
    right, even when TEMPLATE has since changed underneath it for an unrelated reason. That is
    exactly what happened to the version-freeze fix (the `"$CACHE"/*` rejection block that makes
    a pointer inside the install cache advisory rather than authoritative, so an old install
    doesn't silently freeze the engine at whatever version the pointer happened to name): a
    launcher generated before that fix, but AFTER any marketplace rename, already contains the
    current name in full — the old substring test read it as `healthy` and never regenerated it,
    leaving that launcher permanently unable to resolve past a stale in-cache pointer. Comparing
    against `_rendered_template()` byte-for-byte catches that drift and any future one, because
    it asks "would `install()` write something different?" rather than "does the name look ok?".

    ⭐ ONLY ACTS ON AN EXISTING LAUNCHER. A user who never ran `install_launcher.py` (or
    onboarding) gets nothing created here — creating one from nothing stays onboarding's job,
    the same boundary `heal_install.py` draws around installs it did not create.

    SAFE by this module's own rule (migrate.py's docstring): `install()` overwrites a file
    whose own header says "GENERATED ... do not edit; re-run that script instead" — idempotent,
    reversible (re-running install() again is always safe), and carries no user data.

    ⛔⛔ THE GENERATION GUARD — the fix for a regression shipped in 0.33.0 (df068f5), found
    before TEMPLATE next changed but designed to survive the moment it does. This function
    executes as PART OF whichever engine copy imported it, and `migrate.py --hook` runs from the
    session's OWN copy — which is not necessarily the newest installed one. Comparing full
    rendered bytes (the fix this docstring used to describe as the whole story) closes the
    name-substring gap, but opens a worse one: a session running an OLDER engine copy has an
    OLDER `TEMPLATE`, so a launcher a NEWER copy already wrote correctly reads as "drifted" from
    the old copy's point of view — and it would happily rewrite the newer launcher back to
    yesterday's TEMPLATE. Every call to `run` after that regenerates the CURRENT (correct)
    launcher right back into the STALE one, for as long as anything imports the old copy. This
    is inert only because TEMPLATE has not changed again since 0.33.0 shipped — it activates the
    moment it does.

    So: TEMPLATE carries a monotonic `# TEMPLATE_GENERATION: N` header (`_template_generation()`,
    parsed off whatever body is on disk — never off a Python constant a stale copy might
    disagree with). heal_if_stale regenerates only when the ON-DISK generation is **at or below**
    this copy's own; finding a **strictly higher** on-disk generation means a newer copy already
    wrote it, so this refuses outright and records a `stale-copy-session` machine event (never a
    profile one — dev #151) naming both generations. That event is ALSO the detector this
    project otherwise lacks entirely for "a session is running a stale copy": nothing else
    observes it happening. `doctor.py`'s pointer section and `binding.py --assert` both surface
    it. A launcher with no generation marker at all (written before this concept existed) reads
    as older than anything and is healed normally — the guard only ever refuses a STRICTLY newer
    disk generation, never an absent one.

    Returns (verdict, lines). verdict: absent | healthy | healed | would-heal | refused-stale-copy
    | error. Never raises — callers still wrap this in their own envelope, but it stays
    self-contained so it can be tested and called directly.
    """
    if not os.path.exists(LAUNCHER):
        return "absent", []
    try:
        marketplace, plugin = _install_identity()
    except Exception as e:                      # noqa: BLE001 — fails open, deliberately
        return "error", ["  ⚠️ could not derive the current install identity (%s: %s) — "
                         "launcher left unchanged." % (type(e).__name__, e)]
    expected = _rendered_template(marketplace, plugin)
    try:
        with open(LAUNCHER, encoding="utf-8") as fh:
            body = fh.read()
    except OSError as e:
        return "error", ["  ⚠️ could not read %s (%s) — launcher left unchanged." % (LAUNCHER, e)]
    if body == expected:
        return "healthy", []
    disk_gen = _template_generation(body)
    own_gen = _template_generation(TEMPLATE)
    if disk_gen is not None and own_gen is not None and disk_gen > own_gen:
        _diag_machine("stale-copy-session", own_generation=own_gen, disk_generation=disk_gen)
        return "refused-stale-copy", [
            "  ⛔ %s already carries a NEWER template (generation %d) than this engine's own "
            "TEMPLATE (generation %d) — refusing to regenerate it backward." % (
                LAUNCHER, disk_gen, own_gen),
            "     This session is itself running an OLDER installed copy of jobsearch; a newer "
            "copy already updated the launcher. Recorded as a stale-copy-session event — see "
            "`doctor.py` or `binding.py --assert` on this machine."]
    want = "cache/%s/%s" % (marketplace, plugin)
    reason = ("a cache path (not %s) that no longer matches this install, likely left over "
              "from a marketplace rename" % want) if want not in body else (
              "the current install identity, but its generated body has drifted from what "
              "this engine version writes today")
    if not apply_it:
        return "would-heal", [
            "  would regenerate %s — it names %s." % (LAUNCHER, reason)]
    install()
    return "healed", [
        "  ✅ %s regenerated for the current install — it was naming %s." % (LAUNCHER, reason)]


if __name__ == "__main__":
    print("Installed %s" % install())
    print("Engine    %s" % engine_root())
    _v, _lines = record_deliberate_override(sys.argv[1:])
    for _l in _lines:
        print(_l)
    print()
    print("Allowlist this one entry to keep unattended runs from prompting:")
    print('    Bash(~/.claude/jobsearch/run:*)')
    print("`run --where` prints the engine root the launcher resolves, as data.")
